move to the repository of ShellShoccar-jpn

diff --git a/COMMANDS.SH/cgi-name b/COMMANDS.SH/cgi-name
--- a/COMMANDS.SH/cgi-name
+++ b/COMMANDS.SH/cgi-name
@@ -5,15 +5,18 @@
 
 # print the usage and exit
 print_usage_and_exit () {
-	cat <<____USAGE 1>&2
-Usage   : ${0##*/} [-d<c>] [-i<string>] [--template <html>] <param_file>
-Version : Thu Oct 25 01:00:32 JST 2012
-        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
-____USAGE
-	exit 1
+  cat <<-__USAGE 1>&2
+	Usage   : ${0##*/} [-d<c>] [-i<string>] [--template <html>] <param_file>
+	Version : Fri Feb 13 15:06:07 JST 2015
+	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
+__USAGE
+  exit 1
 }
 
 # initialize
+PATH='/usr/bin:/bin'
+export LANG=C
+export LC_ALL=C
 dopt=''
 dopt_is_set=0
 iopt=''
@@ -27,119 +30,123 @@ LF=$(printf '\134\n_'); LF=${LF%_}
 optmode=''
 i=0
 for arg in "$@"; do
-	i=$((i+1))
-	if [ -z "$optmode" ]; then
-		case "$arg" in
-			-d*)
-				dopt_is_set=1
-				optmode='d'
-				if [ -n "${arg#-d}" ]; then
-					arg=${arg#-d}
-				else
-					optmode=''
-					continue
-				fi
-				;;
-			-i*)
-				optmode='i'
-				if [ -n "${arg#-i}" ]; then
-					arg=${arg#-i}
-				else
-					continue
-				fi
-				;;
-			--template)
-				optmode='tmpl'
-				continue
-				;;
-			*)
-				[ $i -eq $# ] || print_usage_and_exit
-				optmode='param'
-				;;
-		esac
-	fi
-	case "$optmode" in
-		d)
-			dopt=$arg
-			optmode=''
-			;;
-		i)
-			iopt=$arg
-			optmode=''
-			;;
-		tmpl)
-			tmpl_file=$arg
-			optmode=''
-			;;
-		param)
-			param_file=$arg
-			optmode=''
-			;;
-	esac
+  i=$((i+1))
+  if [ -z "$optmode" ]; then
+    case "$arg" in
+      -d*)
+        dopt_is_set=1
+        optmode='d'
+        if [ -n "${arg#-d}" ]; then
+          arg=${arg#-d}
+        else
+          optmode=''
+          continue
+        fi
+        ;;
+      -i*)
+        optmode='i'
+        if [ -n "${arg#-i}" ]; then
+          arg=${arg#-i}
+        else
+          continue
+        fi
+        ;;
+      --template)
+        optmode='tmpl'
+        continue
+        ;;
+      *)
+        [ $i -eq $# ] || print_usage_and_exit
+        optmode='param'
+        ;;
+    esac
+  fi
+  case "$optmode" in
+    d)
+      dopt=$arg
+      optmode=''
+      ;;
+    i)
+      iopt=$arg
+      optmode=''
+      ;;
+    tmpl)
+      tmpl_file=$arg
+      optmode=''
+      ;;
+    param)
+      param_file=$arg
+      optmode=''
+      ;;
+  esac
 done
 if [ -z "$param_file" ]; then
-	param_file='-'
+  param_file='-'
 fi
 if [ \( "_$param_file" = '_-'               \) -o \
      \( "_$param_file" = '_/dev/stdin'      \) -o \
      \( "_$param_file" = '_/dev/fd/0'       \) -o \
      \( "_$param_file" = '_/proc/self/fd/0' \)    ]
 then
-	use_stdin=$((use_stdin+1))
+  use_stdin=$((use_stdin+1))
 fi
 if [ \( "_$tmpl_file" = '_-'               \) -o \
      \( "_$tmpl_file" = '_/dev/stdin'      \) -o \
      \( "_$tmpl_file" = '_/dev/fd/0'       \) -o \
      \( "_$tmpl_file" = '_/proc/self/fd/0' \)    ]
 then
-	use_stdin=$((use_stdin+1))
+  use_stdin=$((use_stdin+1))
 fi
 if [ $use_stdin -gt 1 ]; then
-	print_usage_and_exit
+  print_usage_and_exit
 fi
+case "$tmpl_file"  in -|/*|./*|../*) :;; *)  tmpl_file="./$tmpl_file" ;; esac
+case "$param_file" in -|/*|./*|../*) :;; *) param_file="./$param_file";; esac
 if [ \( ! -f "$param_file"     \) -a \
      \( ! -c "$param_file"     \) -a \
+     \( ! -p "$param_file"     \) -a \
      \( "_$param_file" != '_-' \)    ]
 then
-	print_usage_and_exit
+  print_usage_and_exit
 fi
 if [ \( ! -r "$param_file" \) -a \( "_$param_file" != '_-' \) ]; then
-	echo "${0##*/}: Cannot open the file as a param_file" 1>&2
-	exit 1
+  printf '%s\n' "${0##*/}: Cannot open the file as a param_file" 1>&2
+  exit 1
 fi
 
 # operate the --template option
 if [ \( -f "$tmpl_file"      \) -o \
      \( -c "$tmpl_file"      \) -o \
+     \( -p "$tmpl_file"      \) -o \
      \( "_$tmpl_file" = '_-' \)    ]
 then
-	if [ \( ! -r "$tmpl_file" \) -a \( "_$tmpl_file" != '_-' \) ]; then
-		echo "${0##*/}: Cannot open the file as a template file" 1>&2
-		exit 1
-	fi
-	tmplvars=$(cat "$tmpl_file"                                                |
-	           tr '\r\n' '  '                                                  |
-	           sed 's/\(<[Ii][Nn][Pp][Uu][Tt] [^>]*>\)/'"$LF"'\1'"$LF"'</g'    |
-	           grep -i '<input '                                               |
-	           grep -i ' type=["'"'"']\{0,1\}\(radio\>\|checkbox\>\)'          |
-	           grep -i ' name="[^"]*"\| name='"'"'[^'"'"']*'"'"'\| name=[^ ] ' |
-	           sed 's/^.*[Nn][Aa][Mm][Ee]="\([^"]*\)".*$/\1/'                  |
-	           sed 's/^.*[Nn][Aa][Mm][Ee]='"'"'\([^'"'"']*\)'"'"'.*$/\1/'      |
-	           sed 's/^.*[Nn][Aa][Mm][Ee]=\([^ ]*\) .*$/\1/'                   |
-	           grep -v '[^][A-Za-z0-9_.:-]'                                    |
-	           sort                                                            |
-	           uniq                                                            |
-	           tr '\n' ' '                                                     |
-	           sed 's/ $//'                                                    )
+  if [ \( ! -r "$tmpl_file" \) -a \( "_$tmpl_file" != '_-' \) ]; then
+    printf '%s\n' "${0##*/}: Cannot open the file as a template file" 1>&2
+    exit 1
+  fi
+  tmplvars=$(cat "$tmpl_file"                                               |
+             tr '\r\n' '  '                                                 |
+             sed 's/\(<[Ii][Nn][Pp][Uu][Tt] [^>]*>\)/'"$LF"'\1'"$LF"'</g'   |
+             grep -i '<input '                                              |
+             grep -iE ' type=["'"'"']?(radio\>|checkbox\>)'                 |
+             grep -iE ' name="[^"]*"| name='"'"'[^'"'"']*'"'"'| name=[^ ] ' |
+             sed 's/^.*[Nn][Aa][Mm][Ee]="\([^"]*\)".*$/\1/'                 |
+             sed 's/^.*[Nn][Aa][Mm][Ee]='"'"'\([^'"'"']*\)'"'"'.*$/\1/'     |
+             sed 's/^.*[Nn][Aa][Mm][Ee]=\([^ ]*\) .*$/\1/'                  |
+             grep -v '[^][A-Za-z0-9_.:-]'                                   |
+             sort                                                           |
+             uniq                                                           |
+             tr '\n' ' '                                                    |
+             sed 's/ $//'                                                   )
 elif [ -n "$tmpl_file" ]; then
-	print_usage_and_exit
+  print_usage_and_exit
 fi
 
-# transfer the characters to octet escaped strings to import to AWK safely
-octed_dopt=$(echo -n "_$dopt" | od -A n -t o1 | tr -d '\n' | sed 's/^[[:blank:]]*137//' | sed 's/[[:blank:]]*$//' | sed 's/[[:blank:]]\{1,\}/\\/g')
-octed_iopt=$(echo -n "_$iopt" | od -A n -t o1 | tr -d '\n' | sed 's/^[[:blank:]]*137//' | sed 's/[[:blank:]]*$//' | sed 's/[[:blank:]]\{1,\}/\\/g')
-
 # transfer the CGI variables string to the "cgi-name format"
+export v1=$dopt
+export v2=$iopt
+export v3=$dopt_is_set
+export v4=$tmplvars
 cat "$param_file"                                       |
 sed 's/\(%[0-9A-Fa-f][0-9A-Fa-f]\)/'"$LF"'\1'"$LF"'/g'  |
 sed '/^%/y/abcdef/ABCDEF/'                              |
@@ -147,59 +154,61 @@ tr -d '\n'                                              |
 sed 's/%0D%0A/\\n/g'                                    |
 sed 's/&/'"$LF"'/g'                                     |
 sed 's/+/ /'                                            |
-awk -v dopt_is_set=$dopt_is_set -v tmplvars="$tmplvars" '
+exec awk '
 BEGIN {
-	for (i = 0; i < 256; i++) {
-		s = sprintf("%02X",i);
-		chr[s] = sprintf("%c",i);
-	}
-	dopt = sprintf("'"$octed_dopt"'");
-	iopt = sprintf("'"$octed_iopt"'");
-	split(tmplvars, array0);
-	for (var in array0) {
-		tmplvar[array0[var]]="";
-		delete array0[var];
-	}
-	FS = "=";
+  for (i = 0; i < 256; i++) {
+    s = sprintf("%02X",i);
+    chr[s] = sprintf("%c",i);
+  }
+  dopt        = ENVIRON["v1"];
+  iopt        = ENVIRON["v2"];
+  dopt_is_set = ENVIRON["v3"];
+  tmplvars    = ENVIRON["v4"];
+  split(tmplvars, array0);
+  for (var in array0) {
+    tmplvar[array0[var]]="";
+    delete array0[var];
+  }
+  FS = "=";
 }
 {
-	str1 = substr($0, index($0,"=")+1);
-	str2 = "";
-	while (match(str1,/%[0-9A-F][0-9A-F]/)) {
-		hex  = substr(str1, RSTART+1, 2);
-		str2 = str2 substr(str1, 1, RSTART-1) chr[hex];
-		str1 = substr(str1, RSTART+3);
-	}
-	str2 = str2 str1;
+  str1 = substr($0, index($0,"=")+1);
+  str2 = "";
+  while (match(str1,/%[0-9A-F][0-9A-F]/)) {
+    hex  = substr(str1, RSTART+1, 2);
+    str2 = str2 substr(str1, 1, RSTART-1) chr[hex];
+    str1 = substr(str1, RSTART+3);
+  }
+  str2 = str2 str1;
 
-	if (length(str2) == 0 && length(iopt)) {
-		str2 = iopt;
-	} else if (dopt_is_set != 0)  {
-		s = "";
-		while (match(str2,/ /)) {
-			s = s substr(str2, 1, RSTART-1) dopt;
-			str2 = substr(str2, RSTART+1);
-		}
-		str2 = s str2;
-	}
-	if ($1 in tmplvar) {
-		delete tmplvar[$1];
-	}
-	if (length(str2) > 0) {
-		print $1, str2;
-	} else {
-		print $1;
-	}
+  if (length(str2) == 0 && length(iopt)) {
+    str2 = iopt;
+  } else if (dopt_is_set != 0)  {
+    s = "";
+    while (match(str2,/ /)) {
+      s = s substr(str2, 1, RSTART-1) dopt;
+      str2 = substr(str2, RSTART+1);
+    }
+    str2 = s str2;
+  }
+  if ($1 in tmplvar) {
+    delete tmplvar[$1];
+  }
+  if (length(str2) > 0) {
+    print $1, str2;
+  } else {
+    print $1;
+  }
 }
 END {
-	if (length(iopt) > 0) {
-		for (var in tmplvar) {
-			print var, iopt;
-		}
-	} else {
-		for (var in tmplvar) {
-			print var;
-		}
-	}
+  if (length(iopt) > 0) {
+    for (var in tmplvar) {
+      print var, iopt;
+    }
+  } else {
+    for (var in tmplvar) {
+      print var;
+    }
+  }
 }
 '
diff --git a/COMMANDS.SH/cjoin0 b/COMMANDS.SH/cjoin0
--- a/COMMANDS.SH/cjoin0
+++ b/COMMANDS.SH/cjoin0
@@ -5,16 +5,25 @@
 
 # print the usage and exit
 print_usage_and_exit () {
-	cat <<____USAGE 1>&2
-Usage   : ${0##*/} [+ng[<fd>]] key=<n> <master> <tran>
-Version : Thu Dec 25 01:02:01 JST 2012
-        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
-____USAGE
-	exit 1
+  cat <<-__USAGE 1>&2
+	Usage   : ${0##*/} [+ng[<fd>]] key=<n> <master> <tran>
+	Version : Fri Feb 13 15:07:41 JST 2015
+	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
+__USAGE
+  exit 1
 }
+# decide whether to use the alternative length of AWK or not
+if awk 'BEGIN{a[1]=1;b=length(a)}' 2>/dev/null; then
+  arlen='length'
+else
+  arlen='arlen'
+fi
 
 
 # initialize
+PATH='/usr/bin:/bin'
+export LANG=C
+export LC_ALL=C
 ng=''
 key_1=''
 key_2=''
@@ -24,165 +33,172 @@ tranfile=''
 
 # validate the arguments
 for arg in "$@"; do
-	case "$arg" in
-		key=*)
-			key=${arg#key=}
-			key_1=''
-			key_2=''
-			if echo "_$key" | grep '^_[0-9]\{1,\}$' > /dev/null; then
-				s=$(echo $key | sed 's/^0\{1,\}//')
-				[ -z "$s" ] && print_usage_and_exit
-				key_1=$s
-				key_2=$s
-				continue
-			elif echo "_$key" | grep '^_[0-9]\{1,\}/[0-9]\{1,\}$' > /dev/null; then
-				s=$(echo ${key%/*} | sed 's/^0\{1,\}//')
-				[ -z "$s" ] && print_usage_and_exit
-				s1=$(echo ${key#*/} | sed 's/^0\{1,\}//')
-				[ -z "$s1" ] && print_usage_and_exit
-				if [ $s -le $s1 ]; then
-					key_1=$s
-					key_2=$s1
-				else
-					key_1=$s1
-					key_2=$s
-				fi
-				continue
-			elif echo "_$key" | grep '^_[0-9][0-9@]\+[0-9]$' > /dev/null; then
-				echo $arg | grep '@@' > /dev/null && print_usage_and_exit
-				s=$(echo "${key}_" | tr '@' '\n' | sed 's/^0\{1,\}//')
-				echo "$s" | grep '^_*$' > /dev/null && print_usage_and_exit
-				s1=$(echo "${s%_}" | sort -k 1n,1)
-				s2=$(echo "$s1" | uniq)
-				[ "_$s1" != "_$s2" ] && print_usage_and_exit
-				key_1=$(echo "${s%_}" | tr '\n' '@' | sed 's/@$//')
-				key_2=''
-				continue
-			fi
-			print_usage_and_exit
-			;;
-		+ng*)
-			ng=${arg#+ng}
-			if [ -z "$ng" ]; then
-				ng=2
-			elif echo "_$ng" | grep '^_[0-9]\{1,\}$' > /dev/null; then
-				:
-			else
-				print_usage_and_exit
-			fi
-			;;
-		*)
-			if [ -z "$masterfile" ]; then
-				if [ \( -f "$arg" \) -o \( -c "$arg" \) -o \( "_$arg" = '_-' \) ]; then
-					masterfile=$arg
-				fi
-			elif [ -z "$tranfile" ]; then
-				if [ \( -f "$arg" \) -o \( -c "$arg" \) -o \( "_$arg" = '_-' \) ]; then
-					tranfile=$arg
-				fi
-			else
-				print_usage_and_exit
-			fi
-			;;
-	esac
+  case "$arg" in
+    key=*)
+      key=${arg#key=}
+      key_1=''
+      key_2=''
+      if printf '%s\n' "$key" | grep -q '^[0-9]\{1,\}$'; then
+        s=$(echo $key | sed 's/^0\{1,\}//')
+        [ -z "$s" ] && print_usage_and_exit
+        key_1=$s
+        key_2=$s
+        continue
+      elif printf '%s\n' "$key" | grep -q '^[0-9]\{1,\}/[0-9]\{1,\}$'; then
+        s=$(echo ${key%/*} | sed 's/^0\{1,\}//')
+        [ -z "$s" ] && print_usage_and_exit
+        s1=$(echo ${key#*/} | sed 's/^0\{1,\}//')
+        [ -z "$s1" ] && print_usage_and_exit
+        if [ $s -le $s1 ]; then
+          key_1=$s
+          key_2=$s1
+        else
+          key_1=$s1
+          key_2=$s
+        fi
+        continue
+      elif printf '%s\n' "$key" | grep -q '^[0-9][0-9@]\{1,\}[0-9]$'; then
+        printf '%s\n' "$arg" | grep -q '@@' && print_usage_and_exit
+        s=$(echo "${key}_" | tr '@' '\n' | sed 's/^0\{1,\}//')
+        echo "$s" | grep -q '^_*$' && print_usage_and_exit
+        s1=$(echo "${s%_}" | sort -k 1n,1)
+        s2=$(echo "$s1" | uniq)
+        [ "_$s1" != "_$s2" ] && print_usage_and_exit
+        key_1=$(echo "${s%_}" | tr '\n' '@' | sed 's/@$//')
+        key_2=''
+        continue
+      fi
+      print_usage_and_exit
+      ;;
+    +ng*)
+      ng=${arg#+ng}
+      if [ -z "$ng" ]; then
+        ng=2
+      elif printf '%s\n' "$ng" | grep -q '^[0-9]\{1,\}$'; then
+        :
+      else
+        print_usage_and_exit
+      fi
+      ;;
+    *)
+      if [ -z "$masterfile" ]; then
+        if [ \( -f "$arg" \) -o \( -c "$arg" \) -o \( -p "$arg" \) -o \
+             \( "_$arg" = '_-' \)                                     ]; then
+          masterfile=$arg
+        fi
+      elif [ -z "$tranfile" ]; then
+        if [ \( -f "$arg" \) -o \( -c "$arg" \) -o \( -p "$arg" \) -o \
+             \( "_$arg" = '_-' \)                                     ]; then
+          tranfile=$arg
+        fi
+      else
+        print_usage_and_exit
+      fi
+      ;;
+  esac
 done
 if [ -z "$key_1" ]; then
-	print_usage_and_exit
+  print_usage_and_exit
 fi
 if [ -z "$masterfile" ]; then
-	print_usage_and_exit
+  print_usage_and_exit
 fi
 if [ -z "$tranfile" ]; then
-	tranfile='-'
+  tranfile='-'
 fi
 use_stdin=0
 for file in "$masterfile" "$tranfile"; do
-	if [ \( "_$file" = '_-'               \) -o \
-	     \( "_$file" = '_/dev/stdin'      \) -o \
-	     \( "_$file" = '_/dev/fd/0'       \) -o \
-	     \( "_$file" = '_/proc/self/fd/0' \)    ]
-	then
-		use_stdin=$((use_stdin+1))
-	fi
+  if [ \( "_$file" = '_-'               \) -o \
+       \( "_$file" = '_/dev/stdin'      \) -o \
+       \( "_$file" = '_/dev/fd/0'       \) -o \
+       \( "_$file" = '_/proc/self/fd/0' \)    ]
+  then
+    use_stdin=$((use_stdin+1))
+  fi
 done
 if [ $use_stdin -gt 1 ]; then
-	print_usage_and_exit
+  print_usage_and_exit
 fi
 if [ \( ! -r "$masterfile" \) -a \( "_$masterfile" != '_-' \) ]; then
-	echo "${0##*/}: Cannot open the master file" 1>&2
-	exit 1
+  printf '%s\n' "${0##*/}: Cannot open the master file" 1>&2
+  exit 1
 fi
 if [ \( ! -r "$tranfile" \) -a \( "_$tranfile" != '_-' \) ]; then
-	echo "${0##*/}: Cannot open the transaction file" 1>&2
-	exit 1
+  printf '%s\n' "${0##*/}: Cannot open the transaction file" 1>&2
+  exit 1
 fi
+case "$masterfile" in -|/*|./*|../*) :;; *) masterfile="./$masterfile";; esac
+case "$tranfile"   in -|/*|./*|../*) :;; *)   tranfile="./$tranfile"  ;; esac
 
 
 # join
 exec awk -v key_1=$key_1 -v key_2=$key_2 -v ng=$ng \
 '
-	# prepare
-	BEGIN {
-		fd = (ng != "") ? "/dev/fd/"ng : "";
-		if (key_1 == key_2) {
-			keytype = 1;
-			keynum_min = key_1;
-		} else if (key_2 != "") {
-			keytype = 2;
-			keynum_min = key_1;
-		} else {
-			keytype = 3;
-			split(key_1, keynum, "@");
-			keynum_min = keynum[1];
-			for (i = 2; i <= length(keynum); i++) {
-				keynum_min = (keynum[i] < keynum_min) ? keynum[i] : keynum_min;
-			}
-		}
-	}
+  # the alternative length function for array variable
+  function arlen(ar,i,l){for(i in ar){l++;}return l;}
 
-	# print the records in tran which have the same key
-	FNR < NR {
-		if (keytype == 1) {
-			str = "_" $key_1;
-		} else if (keytype == 2) {
-			str = "_";
-			for (i = key_1; i <= key_2; i++) {
-				str = str $i;
-			}
-		} else if (keytype == 3) {
-			str = "_";
-			for (i = 1; i <= length(keynum); i++) {
-				str = str $keynum[i];
-			}
-		} else {
-			str = "_";
-		}
-		if (str in masterkey) {
-			print;
-		} else if (fd != "") {
-			print > fd;
-		}
-		next;
-	}
+  # prepare
+  BEGIN {
+    fd = (ng != "") ? "/dev/fd/"ng : "";
+    if (key_1 == key_2) {
+      keytype = 1;
+      keynum_min = key_1;
+    } else if (key_2 != "") {
+      keytype = 2;
+      keynum_min = key_1;
+    } else {
+      keytype = 3;
+      split(key_1, keynum, "@");
+      keynum_min = keynum[1];
+      for (i = 2; i <= '$arlen'(keynum); i++) {
+        keynum_min = (keynum[i] < keynum_min) ? keynum[i] : keynum_min;
+      }
+    }
+  }
 
-	# load the keys in master
-	{
-		if (keytype == 1) {
-			str = "_" $1;
-		} else if (keytype == 2) {
-			str = "_";
-			for (i = 1; i <= (key_2 - key_1 + 1); i++) {
-				str = str $i;
-			}
-		} else if (keytype == 3) {
-			str = "_";
-			for (i = 1; i <= length(keynum); i++) {
-				j = keynum[i] - keynum_min + 1;
-				str = str $j;
-			}
-		} else {
-			str = "_";
-		}
-		masterkey[str] = 1;
-	}
+  # print the records in tran which have the same key
+  FNR < NR {
+    if (keytype == 1) {
+      str = "_" $key_1;
+    } else if (keytype == 2) {
+      str = "_";
+      for (i = key_1; i <= key_2; i++) {
+        str = str $i;
+      }
+    } else if (keytype == 3) {
+      str = "_";
+      for (i = 1; i <= '$arlen'(keynum); i++) {
+        str = str $keynum[i];
+      }
+    } else {
+      str = "_";
+    }
+    if (str in masterkey) {
+      print;
+    } else if (fd != "") {
+      print > fd;
+    }
+    next;
+  }
+
+  # load the keys in master
+  {
+    if (keytype == 1) {
+      str = "_" $1;
+    } else if (keytype == 2) {
+      str = "_";
+      for (i = 1; i <= (key_2 - key_1 + 1); i++) {
+        str = str $i;
+      }
+    } else if (keytype == 3) {
+      str = "_";
+      for (i = 1; i <= '$arlen'(keynum); i++) {
+        j = keynum[i] - keynum_min + 1;
+        str = str $j;
+      }
+    } else {
+      str = "_";
+    }
+    masterkey[str] = 1;
+  }
 ' "$masterfile" "$tranfile"
diff --git a/COMMANDS.SH/filehame b/COMMANDS.SH/filehame
--- a/COMMANDS.SH/filehame
+++ b/COMMANDS.SH/filehame
@@ -5,15 +5,16 @@
 
 # print the usage and exit
 print_usage_and_exit () {
-	cat <<____USAGE 1>&2
-Usage   : ${0##*/} -l<string> <template> <data>
-Version : Sun Oct 28 03:23:45 JST 2012
-        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
-____USAGE
-	exit 1
+  cat <<-__USAGE 1>&2
+	Usage   : ${0##*/} -l<string> <template> <data>
+	Version : Fri May  9 00:10:52 JST 2014
+	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
+__USAGE
+  exit 1
 }
 
 # initialize
+PATH='/usr/bin:/bin'
 lopt=''
 tmplfile=''
 file=''
@@ -21,94 +22,78 @@ use_stdin=0
 
 # parse arguments
 if [ $# -lt 2 ]; then
-	print_usage_and_exit
+  print_usage_and_exit
 fi
 if [ "_$1" = '_-l' ]; then
-	shift
-	lopt=$1
+  shift
+  lopt=$1
 elif [ \( -n "$1" \) -a \( "_${1#-l}" != "_$1" \) ]; then
-	lopt=${1#-l}
+  lopt=${1#-l}
 else
-	print_usage_and_exit
+  print_usage_and_exit
 fi
 shift
 if [ \( $# -ne 1 \) -a \( $# -ne 2 \) ]; then
-	print_usage_and_exit
+  print_usage_and_exit
 fi
 if [ \( "_$1" = '_-'               \) -o \
      \( "_$1" = '_/dev/stdin'      \) -o \
      \( "_$1" = '_/dev/fd/0'       \) -o \
      \( "_$1" = '_/proc/self/fd/0' \)    ]
 then
-	tmplfile='-'
-	use_stdin=$((use_stdin+1))
-elif [ \( -f "$1" \) -o \( -c "$1" \) ]; then
-	tmplfile=$1
+  tmplfile='-'
+  use_stdin=$((use_stdin+1))
+elif [ \( -f "$1" \) -o \( -c "$1" \) -o \( -p "$1" \) ]; then
+  tmplfile=$1
 else
-	echo "${0##*/}: Invalid template file" 2>&1
-	exit 1
+  echo "${0##*/}: Invalid template file" 2>&1
+  exit 1
 fi
 if [ $# -eq 1 ]; then
-	file='-'
-	use_stdin=$((use_stdin+1))
+  file='-'
+  use_stdin=$((use_stdin+1))
 else
-	if [ \( "_$2" = '_-'               \) -o \
-	     \( "_$2" = '_/dev/stdin'      \) -o \
-	     \( "_$2" = '_/dev/fd/0'       \) -o \
-	     \( "_$2" = '_/proc/self/fd/0' \)    ]
-	then
-		file='-'
-		use_stdin=$((use_stdin+1))
-	elif [ \( -f "$2" \) -o \( -c "$2" \) ]; then
-		file=$2
-	else
-	echo "${0##*/}: Invalid data file" 2>&1
-	exit 1
-	fi
+  if [ \( "_$2" = '_-'               \) -o \
+       \( "_$2" = '_/dev/stdin'      \) -o \
+       \( "_$2" = '_/dev/fd/0'       \) -o \
+       \( "_$2" = '_/proc/self/fd/0' \)    ]
+  then
+    file='-'
+    use_stdin=$((use_stdin+1))
+  elif [ \( -f "$2" \) -o \( -c "$2" \) -o \( -p "$2" \) ]; then
+    file=$2
+  else
+  echo "${0##*/}: Invalid data file" 2>&1
+  exit 1
+  fi
 fi
 if [ $use_stdin -gt 1 ]; then
-	echo "${0##*/}: Both template file and data file request stdin." 2>&1
-	exit 1
+  echo "${0##*/}: Both template file and data file request stdin." 2>&1
+  exit 1
 fi
 if [ \( ! -r "$tmplfile" \) -a \( "_$tmplfile" != '_-' \) ]; then
-	echo "${0##*/}: Cannot open the file as the template file" 1>&2
-	exit 1
+  echo "${0##*/}: Cannot open the file as the template file" 1>&2
+  exit 1
 fi
-if [ -r "$file" ]; then
-	:
-elif [ "_$file" = '_-' ]; then
-	s=$(mktemp -t "${0##*/}.XXXXXXXX")
-	if [ $? -eq 0 ]; then
-		file=$s
-		trap "rm -f $file; exit" EXIT HUP INT QUIT ALRM SEGV TERM
-		cat > "$file"
-	else
-		echo "${0##*/} : Cannot create a temporary file" 1>&2
-		exit 1
-	fi
-else
-	echo "${0##*/}: Cannot open the file as the data file" 1>&2
-	exit 1
+if [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
+  echo "${0##*/}: Cannot open the file as the data file" 1>&2
+  exit 1
 fi
-
-# transfer the characters to octet escaped strings to import to AWK safely
-octed_lopt=$(echo -n "_$lopt" | od -A n -t o1 | tr -d '\n' | sed 's/^[[:blank:]]*137//' | sed 's/[[:blank:]]*$//' | sed 's/[[:blank:]]\{1,\}/\\/g')
-octed_tmplfile=$(echo -n "_$tmplfile" | od -A n -t o1 | tr -d '\n' | sed 's/^[[:blank:]]*137//' | sed 's/[[:blank:]]*$//' | sed 's/[[:blank:]]\{1,\}/\\/g')
-octed_file=$(echo -n "_$file" | od -A n -t o1 | tr -d '\n' | sed 's/^[[:blank:]]*137//' | sed 's/[[:blank:]]*$//' | sed 's/[[:blank:]]\{1,\}/\\/g')
 
 # filehame
-awk '
+# (awk should not be run with "exec" because of having to remove tempfiles)
+v1=$lopt v2=$tmplfile v3=$file awk '
 BEGIN {
-	lopt     = sprintf("'"$octed_lopt"'");
-	tmplfile = sprintf("'"$octed_tmplfile"'");
-	file     = sprintf("'"$octed_file"'");
+  lopt     = ENVIRON["v1"];
+  tmplfile = ENVIRON["v2"];
+  file     = ENVIRON["v3"];
 
-	while (getline tmplline < tmplfile) {
-		if (index(tmplline, lopt)) {
-			system("cat \"" file "\"");
-		} else {
-			print tmplline;
-		}
-	}
+  while (getline tmplline < tmplfile) {
+    if (index(tmplline, lopt)) {
+      system("cat \"" file "\"");
+    } else {
+      print tmplline;
+    }
+  }
 }
 '
diff --git a/COMMANDS.SH/tateyoko b/COMMANDS.SH/tateyoko
--- a/COMMANDS.SH/tateyoko
+++ b/COMMANDS.SH/tateyoko
@@ -5,86 +5,86 @@
 
 # print the usage and exit
 print_usage_and_exit () {
-	cat <<____USAGE 1>&2
-Usage   : ${0##*/} [-d[<string>]] <file>
-Version : Thu Oct 18 22:00:00 JST 2012
-        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
-____USAGE
-	exit 1
+  cat <<-__USAGE 1>&2
+	Usage   : ${0##*/} [-d[<string>]] <file>
+	Version : Fri Jun 27 03:09:40 JST 2014
+	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
+__USAGE
+  exit 1
 }
 
 # initialize
+PATH='/usr/bin:/bin'
 dummy_fldstr=''
 file=''
 
 # parse the arguments
 case "$1" in
-	-d*)
-		dummy_fldstr=${1#-d}
-		if [ "_$dummy_fldstr" = '_' ]; then
-			dummy_fldstr='*'
-		fi
-		shift
-		;;
+  -d*)
+    dummy_fldstr=${1#-d}
+    if [ "_$dummy_fldstr" = '_' ]; then
+      dummy_fldstr='*'
+    fi
+    shift
+    ;;
 esac
-if [ \( -f "$1" \) -o \( -c "$1" \) -o \( "_$1" = '_-' \) ]; then
-	file="$1"
+if [ \( -f "$1" \) -o \( -c "$1" \) -o \( -p "$1" \) -o \
+     \( "_$1" = '_-' \)                                 ]; then
+  file="$1"
 elif [ $# -lt 1 ]; then
-	file='-'
+  file='-'
 else
-	print_usage_and_exit
+  print_usage_and_exit
 fi
 if [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
-	echo "${0##*/}: Cannot open the file" 1>&2
-	exit 1
+  echo "${0##*/}: Cannot open the file" 1>&2
+  exit 1
 fi
 
-# transfer the characters to octet escaped strings to import to AWK safely
-dummy_fldcd=$(echo -n "_$dummy_fldstr" | od -A n -t o1 | tr -d '\n' | sed 's/^[[:blank:]]*137//' | sed 's/[[:blank:]]*$//' | sed 's/[[:blank:]]\{1,\}/\\/g')
-
 # transpose the table
+export v1=$dummy_fldstr
 exec awk '
 BEGIN {
-	max_nf = 0;
-	dummy_fldstr = sprintf("'"$dummy_fldcd"'");
-	_assert_exit = 0;
+  max_nf = 0;
+  dummy_fldstr = ENVIRON["v1"];
+  _assert_exit = 0;
 }
 
 {
-	if (NF > max_nf) {
-		if ((NR > 1) && (length(dummy_fldstr) == 0)) {
-			print "'"${0##*/}"': There is a line which has a differnt number of fields." > "/dev/stderr";
-			_assert_exit = 1;
-			exit _assert_exit;
-		}
-		for (i = max_nf + 1; i <= NF; i++) {
-			tred_line[i] = "";
-			for (j = 1; j < NR; j++) {
-				tred_line[i] = tred_line[i] dummy_fldstr FS;
-			}
-		}
-		max_nf = NF;
-	}
-	for (i = 1; i <= NF; i++) {
-		tred_line[i] = tred_line[i] $i FS;
-	}
-	if (NF < max_nf) {
-		if (length(dummy_fldstr) == 0) {
-			print "'"${0##*/}"': There is a line which has a differnt number of fields." > "/dev/stderr";
-			_assert_exit = 1;
-			exit _assert_exit;
-		}
-		for (i = NF + 1; i <= max_nf; i++) {
-			tred_line[i] = tred_line[i] dummy_fldstr FS;
-		}
-	}
+  if (NF > max_nf) {
+    if ((NR > 1) && (length(dummy_fldstr) == 0)) {
+      print "'"${0##*/}"': There is a line which has a differnt number of fields." > "/dev/stderr";
+      _assert_exit = 1;
+      exit _assert_exit;
+    }
+    for (i = max_nf + 1; i <= NF; i++) {
+      tred_line[i] = "";
+      for (j = 1; j < NR; j++) {
+        tred_line[i] = tred_line[i] dummy_fldstr FS;
+      }
+    }
+    max_nf = NF;
+  }
+  for (i = 1; i <= NF; i++) {
+    tred_line[i] = tred_line[i] $i FS;
+  }
+  if (NF < max_nf) {
+    if (length(dummy_fldstr) == 0) {
+      print "'"${0##*/}"': There is a line which has a differnt number of fields." > "/dev/stderr";
+      _assert_exit = 1;
+      exit _assert_exit;
+    }
+    for (i = NF + 1; i <= max_nf; i++) {
+      tred_line[i] = tred_line[i] dummy_fldstr FS;
+    }
+  }
 }
 END {
-	if (_assert_exit) {
-		exit _assert_exit;
-	}
-	for (i = 1; i <= max_nf; i++) {
-		print substr(tred_line[i], 1, length(tred_line[i]) - length(FS));
-	}
+  if (_assert_exit) {
+    exit _assert_exit;
+  }
+  for (i = 1; i <= max_nf; i++) {
+    print substr(tred_line[i], 1, length(tred_line[i]) - length(FS));
+  }
 }
 ' "$file"
diff --git a/COMMANDS.SH/ycat b/COMMANDS.SH/ycat
--- a/COMMANDS.SH/ycat
+++ b/COMMANDS.SH/ycat
@@ -5,18 +5,38 @@
 
 # print the usage and exit
 print_usage_and_exit () {
-	cat <<____USAGE 1>&2
-Usage   : ${0##*/} [-<n>] <file1> <file2> ...
-Version : Thu Oct 25 01:12:07 JST 2012
-        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
-____USAGE
-	exit 1
+  cat <<-__USAGE 1>&2
+	Usage   : ${0##*/} [-<n>] <file1> <file2> ...
+	Version : Tue Oct 14 18:09:17 JST 2014
+	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
+__USAGE
+  exit 1
 }
+# the alternative of the mktemp command
+which mktemp >/dev/null 2>&1 || {
+  mktemp_fileno=0
+  mktemp() {
+    (
+      mktemp_filename="/tmp/${0##*/}.$$.$mktemp_fileno"
+      mktemp_fileno=$((mktemp_fileno+1))
+      touch "$mktemp_filename"
+      chmod 600 "$mktemp_filename"
+      echo "$mktemp_filename"
+    )
+  }
+}
+# decide whether to use the alternative length of AWK or not
+if awk 'BEGIN{a[1]=1;b=length(a)}' 2>/dev/null; then
+  arlen='length'
+else
+  arlen='arlen'
+fi
 
 
 # initialize
+PATH='/usr/bin:/bin'
 numoption=1
-octed_filenames=''
+filenames=''
 use_stdin=0
 tmpfiles=''
 hexed_filelist=' '
@@ -25,77 +45,84 @@ LF=$(printf '\012_'); LF=${LF%_}
 
 # parse arguments
 mktemp_instead_of_stdin () {
-	tmpfile=$(mktemp -t "${0##*/}.XXXXXXXX")
-	if [ $? -eq 0 ]; then
-		tmpfiles="$tmpfiles $tmpfile"
-		trap "rm -f $tmpfiles; exit" EXIT HUP INT QUIT ALRM SEGV TERM
-		cat > "$tmpfile"
-	else
-		echo "${0##*/} : Cannot create a temporary file" 1>&2
-		exit 1
-	fi
+  tmpfile=$(mktemp -t "${0##*/}.XXXXXXXX")
+  if [ $? -eq 0 ]; then
+    tmpfiles="$tmpfiles $tmpfile"
+    trap "rm -f $tmpfiles; exit" EXIT HUP INT QUIT PIPE ALRM TERM
+    cat > "$tmpfile"
+  else
+    echo "${0##*/}: Cannot create a temporary file" 1>&2
+    exit 1
+  fi
 }
 i=0
 for arg in "$@"; do
-	i=$((i+1))
-	if [ $i -eq 1 ]; then
-		echo "_$arg" | grep '^_-[0-9]\+$' > /dev/null
-		if [ $? -eq 0 ]; then
-			numoption=$(echo "_$arg" | sed 's/^_-//')
-			continue
-		fi
-	fi
-	if [ \( "_$arg" = '_-'               \) -o \
-	     \( "_$arg" = '_/dev/stdin'      \) -o \
-	     \( "_$arg" = '_/dev/fd/0'       \) -o \
-	     \( "_$arg" = '_/proc/self/fd/0' \)    ]
-	then
-		[ $use_stdin -ne 0 ] && print_usage_and_exit
-		use_stdin=1
-		mktemp_instead_of_stdin
-		file=$tmpfile
-	elif [ \( -f "$arg" \) -o \( -c "$arg" \) ]; then
-		str=$(echo -n "_$arg" | sed 's/^_//' | od -A n -t x1 | tr -d ' \n')
-		if echo "$hexed_filelist" | grep -F " $str " > /dev/null; then
-			retry=100
-			while [ $retry -gt 0 ]; do
-				retry=$((retry-1))
-				tmpfile=$(mktemp -u -t "${0##*/}.XXXXXXXX")
-				if [ $? -eq 0 ]; then
-					ln -s "$arg" "$tmpfile" > /dev/null 2>&1
-					[ $? -ne 0 ] && continue
-					tmpfiles="$tmpfiles $tmpfile"
-					trap "rm -f $tmpfiles; exit" EXIT HUP INT QUIT ALRM SEGV TERM
-					break
-				else
-					echo "${0##*/}: Cannot create a temporary file" 1>&2
-					exit 1
-				fi
-			done
-			if [ $retry -eq 0 ]; then
-				echo "${0##*/}: Failed to create a temporary file" 1>&2
-				exit 1
-			fi
-			file=$tmpfile
-		else
-			hexed_filelist="$hexed_filelist$str "
-			file=$arg
-		fi
-	else
-		print_usage_and_exit
-	fi
-	if [ ! -r "$file" ]; then
-		echo "${0##*/}: Cannot open the file \"$arg\"" 1>&2
-		exit 1
-	fi
-	# transfer the characters to octet escaped strings to import to AWK safely
-	octed_filenames="$octed_filenames $(echo -n "_$file" | od -A n -t o1 | tr -d '\n' | sed 's/^[[:blank:]]*137//' | sed 's/[[:blank:]]*$//' | sed 's/[[:blank:]]\{1,\}/\\/g')"
+  i=$((i+1))
+  if [ $i -eq 1 ]; then
+    echo "_$arg" | grep '^_-[0-9]\{1,\}$' > /dev/null
+    if [ $? -eq 0 ]; then
+      numoption=$(echo "_$arg" | sed 's/^_-//')
+      continue
+    fi
+  fi
+  if [ \( "_$arg" = '_-'               \) -o \
+       \( "_$arg" = '_/dev/stdin'      \) -o \
+       \( "_$arg" = '_/dev/fd/0'       \) -o \
+       \( "_$arg" = '_/proc/self/fd/0' \)    ]
+  then
+    [ $use_stdin -ne 0 ] && print_usage_and_exit
+    use_stdin=1
+    mktemp_instead_of_stdin
+    file=$tmpfile
+  elif [ \( -f "$arg" \) -o \( -c "$arg" \) -o \( -p "$arg" \) ]; then
+    str=$(printf '%s' "$arg" |
+          od -v -A n -t x1   |
+          tr -d ' \n'        )
+    if   echo "$hexed_filelist_readonce" | grep -F " $str " >/dev/null; then
+      echo "${0##*/}: Must not be set an irregular file two times" 1>&2
+      exit 1
+    elif echo "$hexed_filelist"          | grep -F " $str " >/dev/null; then
+      retry=100
+      while [ $retry -gt 0 ]; do
+        retry=$((retry-1))
+        tmpfile=$(mktemp -u -t "${0##*/}.XXXXXXXX")
+        if [ $? -eq 0 ]; then
+          ln -s "$arg" "$tmpfile" > /dev/null 2>&1
+          [ $? -ne 0 ] && continue
+          tmpfiles="$tmpfiles $tmpfile"
+          trap "rm -f $tmpfiles; exit" EXIT HUP INT QUIT PIPE ALRM TERM
+          break
+        else
+          echo "${0##*/}: Cannot create a temporary file" 1>&2
+          exit 1
+        fi
+      done
+      if [ $retry -eq 0 ]; then
+        echo "${0##*/}: Failed to create a temporary file" 1>&2
+        exit 1
+      fi
+      file=$tmpfile
+    elif [ -f "$arg" ]; then
+      hexed_filelist="$hexed_filelist$str "
+      file=$arg
+    else
+      hexed_filelist_readonce="$hexed_filelist_readonce$str "
+      file=$arg
+    fi
+  else
+    print_usage_and_exit
+  fi
+  if [ ! -r "$file" ]; then
+    echo "${0##*/}: Cannot open the file \"$arg\"" 1>&2
+    exit 1
+  fi
+  filenames="$filenames $file"
 done
-octed_filenames=${octed_filenames# }
-if [ -z "$octed_filenames" ]; then
-	use_stdin=1
-	mktemp_instead_of_stdin
-	octed_filenames=$(echo -n "_$tmpfile" | od -A n -t o1 | tr -d '\n' | sed 's/^[[:blank:]]*137//' | sed 's/[[:blank:]]*$//' | sed 's/[[:blank:]]\{1,\}/\\/g')
+filenames=${filenames# }
+if [ -z "$filenames" ]; then
+  use_stdin=1
+  mktemp_instead_of_stdin
+  filenames=$tmpfile
 fi
 
 
@@ -103,161 +130,157 @@ fi
 awkcode_func_utf8strlen='
 # strlen for UTF-8 (preparation : you must call this before using utf8strlen)
 function utf8strlen_prep() {
-	utf8strlen_80_1 = sprintf("\200");
-	utf8strlen_C0_X = sprintf("\300");
-	utf8strlen_E0_2 = sprintf("\340");
-	utf8strlen_F0_3 = sprintf("\360");
-	utf8strlen_F8_4 = sprintf("\370");
-	utf8strlen_FC_5 = sprintf("\374");
-	utf8strlen_FE_6 = sprintf("\376");
-	utf8strlen_K_EF = sprintf("\357");
-	utf8strlen_K_BD = sprintf("\275");
-	utf8strlen_K_BE = sprintf("\276");
-	utf8strlen_K_A0 = sprintf("\240");
-	utf8strlen_K_C0 = sprintf("\300");
-	utf8strlen_K_80 = sprintf("\200");
+  utf8strlen_80_1 = sprintf("\200");
+  utf8strlen_C0_X = sprintf("\300");
+  utf8strlen_E0_2 = sprintf("\340");
+  utf8strlen_F0_3 = sprintf("\360");
+  utf8strlen_F8_4 = sprintf("\370");
+  utf8strlen_FC_5 = sprintf("\374");
+  utf8strlen_FE_6 = sprintf("\376");
+  utf8strlen_K_EF = sprintf("\357");
+  utf8strlen_K_BD = sprintf("\275");
+  utf8strlen_K_BE = sprintf("\276");
+  utf8strlen_K_A0 = sprintf("\240");
+  utf8strlen_K_C0 = sprintf("\300");
+  utf8strlen_K_80 = sprintf("\200");
 }
 
 # strlen for UTF-8 (main)
 function utf8strlen(str) {
-	utf8strlen_ = 0;
-	for (utf8strlen_i = 1; utf8strlen_i <= length(str); utf8strlen_i++) {
-		utf8strlen_++;
-		utf8strlen_letter=substr(str, utf8strlen_i, 1);
-		if (utf8strlen_letter < utf8strlen_80_1) {
-			continue;
-		} else if (utf8strlen_letter < utf8strlen_C0_X) {
-			utf8strlen_--;
-			continue;
-		} else if (utf8strlen_letter < utf8strlen_E0_2) {
-			utf8strlen_i++;
-		} else if (utf8strlen_letter < utf8strlen_F0_3) {
-			if (utf8strlen_letter == utf8strlen_K_EF) {
-				utf8strlen_letter2 = substr(str, utf8strlen_i+1, 1);
-				if (utf8strlen_letter2 == utf8strlen_K_BD) {
-					utf8strlen_letter3 = substr(str, utf8strlen_i+2, 1);
-					if ((utf8strlen_letter3 >= utf8strlen_K_A0) &&
-					    (utf8strlen_letter3 <  utf8strlen_K_C0)  ) {
-						utf8strlen_--;
-					}
-				} else if (utf8strlen_letter2 == utf8strlen_K_BE) {
-					utf8strlen_letter3 = substr(str, utf8strlen_i+2, 1);
-					if ((utf8strlen_letter3 >= utf8strlen_K_80) &&
-					    (utf8strlen_letter3 <  utf8strlen_K_A0)  ) {
-						utf8strlen_--;
-					}
-				}
-			}
-			utf8strlen_i += 2;
-		} else if (utf8strlen_letter < utf8strlen_F8_4) {
-			utf8strlen_i += 3;
-		} else if (utf8strlen_letter < utf8strlen_FC_5) {
-			utf8strlen_i += 4;
-		} else if (utf8strlen_letter < utf8strlen_FE_6) {
-			utf8strlen_i += 5;
-		} else {
-			utf8strlen_--;
-			continue;
-		}
-		utf8strlen_++;
-	}
-	return utf8strlen_;
+  utf8strlen_ = 0;
+  for (utf8strlen_i = 1; utf8strlen_i <= length(str); utf8strlen_i++) {
+    utf8strlen_++;
+    utf8strlen_letter=substr(str, utf8strlen_i, 1);
+    if (utf8strlen_letter < utf8strlen_80_1) {
+      continue;
+    } else if (utf8strlen_letter < utf8strlen_C0_X) {
+      utf8strlen_--;
+      continue;
+    } else if (utf8strlen_letter < utf8strlen_E0_2) {
+      utf8strlen_i++;
+    } else if (utf8strlen_letter < utf8strlen_F0_3) {
+      if (utf8strlen_letter == utf8strlen_K_EF) {
+        utf8strlen_letter2 = substr(str, utf8strlen_i+1, 1);
+        if (utf8strlen_letter2 == utf8strlen_K_BD) {
+          utf8strlen_letter3 = substr(str, utf8strlen_i+2, 1);
+          if ((utf8strlen_letter3 >= utf8strlen_K_A0) &&
+              (utf8strlen_letter3 <  utf8strlen_K_C0)  ) {
+            utf8strlen_--;
+          }
+        } else if (utf8strlen_letter2 == utf8strlen_K_BE) {
+          utf8strlen_letter3 = substr(str, utf8strlen_i+2, 1);
+          if ((utf8strlen_letter3 >= utf8strlen_K_80) &&
+              (utf8strlen_letter3 <  utf8strlen_K_A0)  ) {
+            utf8strlen_--;
+          }
+        }
+      }
+      utf8strlen_i += 2;
+    } else if (utf8strlen_letter < utf8strlen_F8_4) {
+      utf8strlen_i += 3;
+    } else if (utf8strlen_letter < utf8strlen_FC_5) {
+      utf8strlen_i += 4;
+    } else if (utf8strlen_letter < utf8strlen_FE_6) {
+      utf8strlen_i += 5;
+    } else {
+      utf8strlen_--;
+      continue;
+    }
+    utf8strlen_++;
+  }
+  return utf8strlen_;
 }
 '
 
 
 # get the maximal widthes of the files
 awkcode_main1_get_maxwidthes='
+# the alternative length function for array variable
+function arlen(ar,i,l){for(i in ar){l++;}return l;}
+
 BEGIN {
-	utf8strlen_prep();
+  utf8strlen_prep();
 
-	split(octed_filenames, octed_filename);
-	for (i = 1; i <= length(octed_filename); i++) {
-		filename[i] = sprintf(octed_filename[i]);
-	}
+  filenames = ENVIRON["v1"];
+  split(filenames, filename);
 
-	for (i = 1; i <= length(filename); i++) {
-		maxwidth[i] = 0;
-		while (getline str < filename[i]) {
-			width = utf8strlen(str);
-			if (width > maxwidth[i]) {
-				maxwidth[i] = width;
-			}
-		}
-		close(filename[i]);
-	}
+  for (i = 1; i <= '$arlen'(filename); i++) {
+    maxwidth[i] = 0;
+    while (getline str < filename[i]) {
+      width = utf8strlen(str);
+      if (width > maxwidth[i]) {
+        maxwidth[i] = width;
+      }
+    }
+    close(filename[i]);
+  }
 
-	str = "";
-	for (i = 1; i <= length(maxwidth); i++) {
-		str = str " " maxwidth[i];
-	}
-	print substr(str, 2, length(str) - 1);
+  str = "";
+  for (i = 1; i <= '$arlen'(maxwidth); i++) {
+    str = str " " maxwidth[i];
+  }
+  print substr(str, 2, length(str) - 1);
 }
 '
-max_widthes=$(awk -v "octed_filenames=$octed_filenames" "$awkcode_main1_get_maxwidthes$awkcode_func_utf8strlen")
+max_widthes=$(v1=$filenames awk "$awkcode_main1_get_maxwidthes$awkcode_func_utf8strlen")
 
 
 # ycat
 awkcode_main2_ycat='
+# the alternative length function for array variable
+function arlen(ar,i,l){for(i in ar){l++;}return l;}
+
 BEGIN {
-	utf8strlen_prep();
+  utf8strlen_prep();
 
-	split(octed_filenames, octed_filename);
-	for (i = 1; i <= length(octed_filename); i++) {
-		filename[i] = sprintf(octed_filename[i]);
-	}
+  filenames   = ENVIRON["v1"];
+  numoption   = ENVIRON["v2"];
+  max_widthes = ENVIRON["v3"];
+  split(filenames, filename);
+  split(max_widthes, max_width);
 
-	split(max_widthes, max_width);
-
-	margin = "";
-	for (i = 0; i < numoption; i++) {
-		margin = margin FS;
-	}
-	while (1) {
-		line = "";
-		validlines = 0;
-		for (i = 1; i <= length(filename); i++) {
-			if (length(filename[i])) {
-				if (getline str < filename[i]) {
-					validlines++;
-				} else {
-					close(filename[i]);
-					filename[i] = "";
-					str = "";
-				}
-			} else {
-				str = "";
-			}
-			padding = "";
-			j = max_width[i] - utf8strlen(str);
-			if (j > 0) {
-				padding = sprintf("%0" j "d", 0);
-				gsub("0", " ", padding);
-			}
-			line = (i == 1) ? str padding : line margin str padding;
-		}
-		if (validlines) {
-			print line;
-			continue;
-		}
-		else {
-			break;
-		}
-	}
+  margin = "";
+  for (i = 0; i < numoption; i++) {
+    margin = margin FS;
+  }
+  while (1) {
+    line = "";
+    validlines = 0;
+    for (i = 1; i <= '$arlen'(filename); i++) {
+      if (length(filename[i])) {
+        if (getline str < filename[i]) {
+          validlines++;
+        } else {
+          close(filename[i]);
+          filename[i] = "";
+          str = "";
+        }
+      } else {
+        str = "";
+      }
+      padding = "";
+      j = max_width[i] - utf8strlen(str);
+      if (j > 0) {
+        padding = sprintf("%0" j "d", 0);
+        gsub("0", " ", padding);
+      }
+      line = (i == 1) ? str padding : line margin str padding;
+    }
+    if (validlines) {
+      print line;
+      continue;
+    }
+    else {
+      break;
+    }
+  }
 }
 '
-if [ -z "$LC_ALL" ]; then
-	LC_CTYPE=C;          export LC_CTYPE
-else
-	LANG=$LC_ALL;        export LANG
-	LC_COLLATE=$LC_ALL;  export LC_COLLATE
-	LC_MESSAGES=$LC_ALL; export LC_MESSAGES
-	LC_NUMERIC=$LC_ALL;  export LC_NUMERIC
-	LC_CTYPE=C;          export LC_CTYPE
-	unset LC_ALL
-fi
 if [ -z "$tmpfiles" ]; then
-	exec awk -v numoption=$numoption -v "octed_filenames=$octed_filenames" -v "max_widthes=$max_widthes" "$awkcode_main2_ycat$awkcode_func_utf8strlen"
+  exec env -i v1="$filenames" v2="$numoption" v3="$max_widthes" \
+       awk "$awkcode_main2_ycat$awkcode_func_utf8strlen"
 else
-	awk -v numoption=$numoption -v "octed_filenames=$octed_filenames" -v "max_widthes=$max_widthes" "$awkcode_main2_ycat$awkcode_func_utf8strlen"
+  # (awk should not be run with "exec" because of having to remove tempfiles)
+  env -i v1="$filenames" v2="$numoption" v3="$max_widthes" \
+  awk "$awkcode_main2_ycat$awkcode_func_utf8strlen"
 fi
