self,cjoin[01]:some improved cjoin2:added

diff --git a/COMMANDS.SH/cjoin0 b/COMMANDS.SH/cjoin0
--- a/COMMANDS.SH/cjoin0
+++ b/COMMANDS.SH/cjoin0
@@ -6,27 +6,24 @@
 # print the usage and exit
 print_usage_and_exit () {
   cat <<-__USAGE 1>&2
-	Usage   : ${0##*/} [+ng[<fd>]] key=<n> <master> <tran>
-	Version : Fri Feb 13 15:07:41 JST 2015
-	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
+	Usage   : ${0##*/} [+ng[<fd>]] key=<key> <master> <tran>
+	Version : Sun Jun 14 22:51:26 JST 2015
+	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
 __USAGE
   exit 1
 }
-# decide whether to use the alternative length of AWK or not
-if awk 'BEGIN{a[1]=1;b=length(a)}' 2>/dev/null; then
-  arlen='length'
-else
-  arlen='arlen'
-fi
 
 
 # initialize
 PATH='/usr/bin:/bin'
-export LANG=C
-export LC_ALL=C
+IFS=$(printf ' \t\n_'); IFS=${IFS%_}
+export LANG=C LC_ALL=C
+LF=$(printf '\\\n_');LF=${LF%_}
+set -u
 ng=''
-key_1=''
-key_2=''
+key=''
+fldstr_t=''
+flds=''
 masterfile=''
 tranfile=''
 
@@ -36,49 +33,17 @@ for arg in "$@"; do
   case "$arg" in
     key=*)
       key=${arg#key=}
-      key_1=''
-      key_2=''
-      if printf '%s\n' "$key" | grep -q '^[0-9]\{1,\}$'; then
-        s=$(echo $key | sed 's/^0\{1,\}//')
-        [ -z "$s" ] && print_usage_and_exit
-        key_1=$s
-        key_2=$s
-        continue
-      elif printf '%s\n' "$key" | grep -q '^[0-9]\{1,\}/[0-9]\{1,\}$'; then
-        s=$(echo ${key%/*} | sed 's/^0\{1,\}//')
-        [ -z "$s" ] && print_usage_and_exit
-        s1=$(echo ${key#*/} | sed 's/^0\{1,\}//')
-        [ -z "$s1" ] && print_usage_and_exit
-        if [ $s -le $s1 ]; then
-          key_1=$s
-          key_2=$s1
-        else
-          key_1=$s1
-          key_2=$s
-        fi
-        continue
-      elif printf '%s\n' "$key" | grep -q '^[0-9][0-9@]\{1,\}[0-9]$'; then
-        printf '%s\n' "$arg" | grep -q '@@' && print_usage_and_exit
-        s=$(echo "${key}_" | tr '@' '\n' | sed 's/^0\{1,\}//')
-        echo "$s" | grep -q '^_*$' && print_usage_and_exit
-        s1=$(echo "${s%_}" | sort -k 1n,1)
-        s2=$(echo "$s1" | uniq)
-        [ "_$s1" != "_$s2" ] && print_usage_and_exit
-        key_1=$(echo "${s%_}" | tr '\n' '@' | sed 's/@$//')
-        key_2=''
-        continue
-      fi
-      print_usage_and_exit
+      case "$key" in *NF*)
+        printf '%s\n' "${0##*/}: Cannot use NF in the key argument" 1>&2
+        exit 1
+        ;;
+      esac
       ;;
     +ng*)
       ng=${arg#+ng}
-      if [ -z "$ng" ]; then
-        ng=2
-      elif printf '%s\n' "$ng" | grep -q '^[0-9]\{1,\}$'; then
-        :
-      else
-        print_usage_and_exit
-      fi
+      case "$ng" in '') ng=2;; esac
+      case "$ng" in *[^0-9]*) print_usage_and_exit;; esac
+      ng=$((ng+0))
       ;;
     *)
       if [ -z "$masterfile" ]; then
@@ -97,15 +62,9 @@ for arg in "$@"; do
       ;;
   esac
 done
-if [ -z "$key_1" ]; then
-  print_usage_and_exit
-fi
-if [ -z "$masterfile" ]; then
-  print_usage_and_exit
-fi
-if [ -z "$tranfile" ]; then
-  tranfile='-'
-fi
+case "$key"        in '') print_usage_and_exit;; esac
+case "$masterfile" in '') print_usage_and_exit;; esac
+case "$tranfile"   in '') print_usage_and_exit;; esac
 use_stdin=0
 for file in "$masterfile" "$tranfile"; do
   if [ \( "_$file" = '_-'               \) -o \
@@ -130,75 +89,216 @@ fi
 case "$masterfile" in -|/*|./*|../*) :;; *) masterfile="./$masterfile";; esac
 case "$tranfile"   in -|/*|./*|../*) :;; *)   tranfile="./$tranfile"  ;; esac
 
+# validate the "key" argument and make the fields to compare from it
+dlm=''
+for arg in $(printf '%s\n' "$key" | tr '@' ' '); do
+  # "/" extraction mode (make arg2 if this mode)
+  arg1=${arg%%/*}
+  arg2=${arg##*/}
+  if [ \( "_${arg1}/${arg2}" = "_$arg"   \) -a \
+       \( -n "$arg1" \) -a \( -n "$arg2" \)    ]
+  then
+    break
+  else
+    arg2=''
+  fi
+  # get substr parameters from arg1 if possible
+  stpos=0
+  edpos=-1
+  arg1s=${arg1#*.}
+  arg1=${arg1%%.*}
+  if [ "_$arg1s" != "_$arg1" ]; then
+    if printf '%s\n' "$arg1s" | grep -q '^[0-9]\{1,\}$'; then
+      stpos=$arg1s
+      if [ $stpos -eq 0 ]; then
+        break
+      fi
+    elif printf '%s\n' "$arg1s" | grep -q '^[0-9]\{1,\}\.[0-9]\{1,\}$'; then
+      stpos=${arg1s%.*}
+      edpos=${arg1s#*.}
+      if [ $stpos -eq 0 ]; then
+        break
+      fi
+    else
+      break
+    fi
+  fi
+  # judge the field number type of arg1 (also arg2 if possible)
+  if printf '%s\n' "$arg1" | grep -q '^[0-9]\{1,\}$'; then
+    arg1type=1
+  else
+    arg1type=-1
+  fi
+  if [ -z "$arg2" ]; then
+    arg2type=0
+  elif printf '%s\n' "$arg2" | grep -q '^[0-9]\{1,\}$'; then
+    arg2type=1
+  else
+    arg2type=-1
+  fi
+  if [ \( $arg1type -lt 0 \) -o \( $arg2type -lt 0 \) ]; then
+    break
+  fi
+  # generate the string for the AWK-print
+  if [ $arg2type -eq 0 ]; then
+    if [ $stpos -eq 0 ]; then
+      if [ $arg1type -eq 1 ]; then
+        fldstr_t="$fldstr_t$dlm\$$arg1"
+      else
+        fldstr_t="$fldstr_t$dlm\$($arg1)"
+      fi
+    else
+      if [ $arg1type -eq 1 ]; then
+        fldstr_t="$fldstr_t${dlm}getsubf(\$$arg1,$stpos,$edpos)"
+      else
+        fldstr_t="$fldstr_t${dlm}getsubf(\$($arg1),$stpos,$edpos)"
+      fi
+    fi
+  else
+    if [ \( $stpos -eq 0 \) -a \( $arg1 -le $arg2 \) ]; then
+      j=$arg1
+      while [ $j -le $arg2 ]; do
+        fldstr_t="$fldstr_t${dlm}\$$j"
+        dlm=' FS '
+        j=$((j+1))
+      done
+    elif [ \( $stpos -eq 0 \) -a \( $arg1 -ge $arg2 \) ]; then
+      j=$arg1
+      while [ $j -ge $arg2 ]; do
+        fldstr_t="$fldstr_t${dlm}\$$j"
+        dlm=' FS '
+        j=$((j-1))
+      done
+    elif [ \( $stpos -ne 0 \) -a \( $arg1 -le $arg2 \) ]; then
+      j=$arg1
+      while [ $j -le $arg2 ]; do
+        fldstr_t="$fldstr_t${dlm}getsubf(\$$j,$stpos,$edpos)"
+        dlm=' FS '
+        j=$((j+1))
+      done
+    elif [ \( $stpos -ne 0 \) -a \( $arg1 -ge $arg2 \) ]; then
+      j=$arg1
+      while [ $j -ge $arg2 ]; do
+        fldstr_t="$fldstr_t${dlm}getsubf(\$$j,$stpos,$edpos)"
+        dlm=' FS '
+        j=$((j-1))
+      done
+    fi
+  fi
+  # loop
+  arg=''
+  dlm=' FS '
+done
+case "$fldstr_t" in '') print_usage_and_exit;; esac
+flds_t=$(echo "$fldstr_t"                               |
+         sed 's/\$/'"$LF"'$/g'                          |
+         sed -n '/^\$/{s/^\$\([0-9]\{1,\}\).*$/\1/;p;}' |
+         sort -k 1n,1 -u                                |
+         tr '\n' ' '                                    |
+         sed 's/ $//'                                   )
+minfldnum=${flds_t%% *}
+fldstr_m=$(echo "$fldstr_t"                                           |
+           sed 's/\$[0-9]\{1,\}/'"$LF"'&'"$LF"'/g'                    |
+           awk '/^\$/{print "$" substr($0,2)+1-'$minfldnum';next;} 1' |
+           tr -d '\n'                                                 )
+
 
 # join
-exec awk -v key_1=$key_1 -v key_2=$key_2 -v ng=$ng \
+exec awk -v ng=$ng \
 '
-  # the alternative length function for array variable
-  function arlen(ar,i,l){for(i in ar){l++;}return l;}
+  # getsubf (preparation : you must call this before using the "getsubf")
+  function utf8_prep() {
+    chr_80_1 = sprintf("\200");
+    chr_C0_X = sprintf("\300");
+    chr_E0_2 = sprintf("\340");
+    chr_F0_3 = sprintf("\360");
+    chr_F8_4 = sprintf("\370");
+    chr_FC_5 = sprintf("\374");
+    chr_FE_6 = sprintf("\376");
+    chr_K_EF = sprintf("\357");
+    chr_K_BD = sprintf("\275");
+    chr_K_BE = sprintf("\276");
+    chr_K_A0 = sprintf("\240");
+    chr_K_C0 = sprintf("\300");
+    chr_K_80 = sprintf("\200");
+  }
+  # return the substr in accordance with the counting rule of self command
+  function getsubf(str, startpos, len  ,i,p,l,l2,l3,st,ed) {
+    # - "st" is a byte offset (start from 1) which the
+    #   "startpos" suggests by the Japanese text position (zenkaku-hankaku;
+    #   start from 1)
+    # - "ed" is a byte offset + 1 (start from 1) which the
+    #   "len" suggests by the Japanese text width (zenkaku-hankaku;
+    #   start from 1; -1 means "to the end")
+    st = 0;
+    ed = 0;
+    #
+    # - "i" is a byte offset (start from 1) from which the function
+    #   will read now
+    # - "l" is a Japanese text position (zenkaku-hankaku; start
+    #   from 1) of the letter which the function will read
+    i = 1;
+    p = 1;
+    while (i <= length(str)) {
+      if (st == 0) {
+        if (startpos == p) {
+          st = i;
+          if (len == -1) {break;}
+        } else if (startpos < p) {
+          _assert_exit = 1;
+          exit _assert_exit;
+        }
+      }
+      l = substr(str, i, 1);
+      if        (l < chr_80_1) {i++; p++;
+      } else if (l < chr_C0_X) {i++; # invalid UTF-8
+      } else if (l < chr_E0_2) {i += 2; p += 2;
+      } else if (l < chr_F0_3) {
+        if (l == chr_K_EF) {
+          l2 = substr(str, i+1, 1);
+          if        (l2 == chr_K_BD) {
+            l3 = substr(str, i+2, 1);
+            if ((l3 >= chr_K_A0) && (l3 < chr_K_C0)) {p += 1;
+            } else                                   {p += 2;}
+          } else if (l2 == chr_K_BE) {
+            l3 = substr(str, i+2, 1);
+            if ((l3 >= chr_K_80) && (l3 < chr_K_A0)) {p += 1;
+            } else                                   {p += 2;}
+          } else                     {p += 2;                 }
+        } else             {p += 2;                            }
+        i += 3;
+      } else if (l < chr_F8_4) {i += 4; p += 2;
+      } else if (l < chr_FC_5) {i += 5; p += 2;
+      } else if (l < chr_FE_6) {i += 6; p += 2;
+      } else                   {i++;                            } # invalidUTF-8
+      if (st > 0) {
+        if        ((startpos + len) == p) {ed = i ; break;
+        } else if (len == 0)              {ed = st; break;
+        } else if ((startpos + len) <  p) {_assert_exit = 1; exit _assert_exit;}
+      }
+    }
+    if (st == 0) {_assert_exit = 1; exit _assert_exit;}
+    return (ed == 0) ? substr(str,st) : substr(str,st,ed-st);
+  }
+
+  # ==================================================================
 
   # prepare
   BEGIN {
-    fd = (ng != "") ? "/dev/fd/"ng : "";
-    if (key_1 == key_2) {
-      keytype = 1;
-      keynum_min = key_1;
-    } else if (key_2 != "") {
-      keytype = 2;
-      keynum_min = key_1;
-    } else {
-      keytype = 3;
-      split(key_1, keynum, "@");
-      keynum_min = keynum[1];
-      for (i = 2; i <= '$arlen'(keynum); i++) {
-        keynum_min = (keynum[i] < keynum_min) ? keynum[i] : keynum_min;
-      }
-    }
+    fd = (ng != "") ? "/dev/fd/" ng : "";
+    utf8_prep();
   }
 
   # print the records in tran which have the same key
   FNR < NR {
-    if (keytype == 1) {
-      str = "_" $key_1;
-    } else if (keytype == 2) {
-      str = "_";
-      for (i = key_1; i <= key_2; i++) {
-        str = str $i;
-      }
-    } else if (keytype == 3) {
-      str = "_";
-      for (i = 1; i <= '$arlen'(keynum); i++) {
-        str = str $keynum[i];
-      }
-    } else {
-      str = "_";
-    }
-    if (str in masterkey) {
-      print;
-    } else if (fd != "") {
-      print > fd;
-    }
+    key_str = '"$fldstr_t"';
+    if        (key_str in masterkey) {print;
+    } else if (fd != ""            ) {print > fd;}
     next;
   }
 
   # load the keys in master
   {
-    if (keytype == 1) {
-      str = "_" $1;
-    } else if (keytype == 2) {
-      str = "_";
-      for (i = 1; i <= (key_2 - key_1 + 1); i++) {
-        str = str $i;
-      }
-    } else if (keytype == 3) {
-      str = "_";
-      for (i = 1; i <= '$arlen'(keynum); i++) {
-        j = keynum[i] - keynum_min + 1;
-        str = str $j;
-      }
-    } else {
-      str = "_";
-    }
-    masterkey[str] = 1;
+    masterkey['"$fldstr_m"'] = 1;
   }
 ' "$masterfile" "$tranfile"
diff --git a/COMMANDS.SH/self b/COMMANDS.SH/self
--- a/COMMANDS.SH/self
+++ b/COMMANDS.SH/self
@@ -8,7 +8,7 @@ print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} <f1> <f2> ... <file>
 	        : ${0##*/} -d <f1> <f2> ... <string>
-	Version : Sun Jul 13 03:10:28 JST 2014
+	Version : Mon Jun 15 01:14:15 JST 2015
 	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
 __USAGE
   exit 1
@@ -16,6 +16,8 @@ __USAGE
 
 # initialize
 PATH='/usr/bin:/bin'
+IFS=$(printf ' \t\n_'); IFS=${IFS%_}
+export IFS LANG=C LC_ALL=C PATH
 directmode=0
 directstr=''
 awkprstr=''
@@ -41,7 +43,7 @@ for arg in "$@"; do
   if [ \( "_${arg1}/${arg2}" = "_$arg"   \) -a \
        \( -n "$arg1" \) -a \( -n "$arg2" \)    ]
   then
-    if echo "_$arg2" | grep -E '^_(NF|(NF-)?[0-9]+)$' > /dev/null; then
+    if printf '%s\n' "$arg2" | grep -Eq '^(NF|(NF-)?[0-9]+)$'; then
       :
     else
       break
@@ -55,12 +57,12 @@ for arg in "$@"; do
   arg1s=${arg1#*.}
   arg1=${arg1%%.*}
   if [ "_$arg1s" != "_$arg1" ]; then
-    if echo "_$arg1s" | grep '^_[0-9]\{1,\}$' > /dev/null; then
+    if printf '%s\n' "$arg1s" | grep -q '^[0-9]\{1,\}$'; then
       stpos=$arg1s
       if [ $stpos -eq 0 ]; then
         break
       fi
-    elif echo "_$arg1s" | grep '^_[0-9]\{1,\}\.[0-9]\{1,\}$' > /dev/null; then
+    elif printf '%s\n' "$arg1s" | grep -q '^[0-9]\{1,\}\.[0-9]\{1,\}$'; then
       stpos=${arg1s%.*}
       edpos=${arg1s#*.}
       if [ $stpos -eq 0 ]; then
@@ -71,18 +73,18 @@ for arg in "$@"; do
     fi
   fi
   # judge the field number type of arg1 (also arg2 if possible)
-  if echo "_$arg1" | grep '^_[0-9]\{1,\}$' > /dev/null; then
+  if printf '%s\n' "$arg1" | grep -q '^[0-9]\{1,\}$'; then
     arg1type=1
-  elif echo "_$arg1" | grep -E '^_(NF|NF-[0-9]+)$' > /dev/null; then
+  elif printf '%s\n' "$arg1" | grep -Eq '^(NF|NF-[0-9]+)$'; then
     arg1type=2
   else
     arg1type=-1
   fi
   if [ -z "$arg2" ]; then
     arg2type=0
-  elif echo "_$arg2" | grep '^_[0-9]\{1,\}$' > /dev/null; then
+  elif printf '%s\n' "$arg2" | grep -q '^[0-9]\{1,\}$'; then
     arg2type=1
-  elif echo "_$arg2" | grep -E '^_(NF|NF-[0-9]+)$' > /dev/null; then
+  elif printf '%s\n' "$arg2" | grep -Eq '^(NF|NF-[0-9]+)$'; then
     arg2type=2
   else
     arg2type=-1
@@ -217,7 +219,7 @@ fi
 if [ $directmode -ne 0 ]; then
   file=''
 elif [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
-  echo "${0##*/}: Cannot open the file" 1>&2
+  printf '%s\n' "${0##*/}: Cannot open the file" 1>&2
   exit 1
 fi
 
@@ -242,152 +244,112 @@ END {
 
 # getsubf (preparation : you must call this before using the "getsubf")
 function getsubf_prep() {
-  getsubf_80_1 = sprintf("\200");
-  getsubf_C0_X = sprintf("\300");
-  getsubf_E0_2 = sprintf("\340");
-  getsubf_F0_3 = sprintf("\360");
-  getsubf_F8_4 = sprintf("\370");
-  getsubf_FC_5 = sprintf("\374");
-  getsubf_FE_6 = sprintf("\376");
-  getsubf_K_EF = sprintf("\357");
-  getsubf_K_BD = sprintf("\275");
-  getsubf_K_BE = sprintf("\276");
-  getsubf_K_A0 = sprintf("\240");
-  getsubf_K_C0 = sprintf("\300");
-  getsubf_K_80 = sprintf("\200");
+  chr_80_1 = sprintf("\200");
+  chr_C0_X = sprintf("\300");
+  chr_E0_2 = sprintf("\340");
+  chr_F0_3 = sprintf("\360");
+  chr_F8_4 = sprintf("\370");
+  chr_FC_5 = sprintf("\374");
+  chr_FE_6 = sprintf("\376");
+  chr_K_EF = sprintf("\357");
+  chr_K_BD = sprintf("\275");
+  chr_K_BE = sprintf("\276");
+  chr_K_A0 = sprintf("\240");
+  chr_K_C0 = sprintf("\300");
+  chr_K_80 = sprintf("\200");
 }
 # return the substr in accordance with the counting rule of self command
-function getsubf(str, startpos, len) {
-  # - "getsubf_substr_s" is a byte offset (start from 1) which the
+function getsubf(str, startpos, len  ,i,p,l,l2,l3,st,ed) {
+  # - "st" is a byte offset (start from 1) which the
   #   "startpos" suggests by the Japanese text position (zenkaku-hankaku;
   #   start from 1)
-  # - "getsubf_substr_e" is a byte offset + 1 (start from 1) which the
+  # - "ed" is a byte offset + 1 (start from 1) which the
   #   "len" suggests by the Japanese text width (zenkaku-hankaku;
   #   start from 1; -1 means "to the end")
-  getsubf_substr_s = 0;
-  getsubf_substr_e = 0;
+  st = 0;
+  ed = 0;
   #
-  # - "getsubf"_i is a byte offset (start from 1) from which the function
+  # - "i" is a byte offset (start from 1) from which the function
   #   will read now
-  # - "getsubf_pos" is a Japanese text position (zenkaku-hankaku; start
+  # - "l" is a Japanese text position (zenkaku-hankaku; start
   #   from 1) of the letter which the function will read
-  getsubf_i   = 1;
-  getsubf_pos = 1;
-  while (getsubf_i <= length(str)) {
-    if (getsubf_substr_s == 0) {
-      if (startpos == getsubf_pos) {
-        getsubf_substr_s = getsubf_i;
-        if (len == -1) {
-          break;
-        }
-      } else if (startpos < getsubf_pos) {
+  i = 1;
+  p = 1;
+  while (i <= length(str)) {
+    if (st == 0) {
+      if (startpos == p) {
+        st = i;
+        if (len == -1) {break;}
+      } else if (startpos < p) {
         _assert_exit = 1;
         exit _assert_exit;
       }
     }
-    getsubf_letter = substr(str, getsubf_i, 1);
-    if (getsubf_letter < getsubf_80_1) {
-      getsubf_i++;
-      getsubf_pos++;
-    } else if (getsubf_letter < getsubf_C0_X) {
-      # invalid UTF-8 character
-      getsubf_i++;
-    } else if (getsubf_letter < getsubf_E0_2) {
-      getsubf_i   += 2;
-      getsubf_pos += 2;
-    } else if (getsubf_letter < getsubf_F0_3) {
-      if (getsubf_letter == getsubf_K_EF) {
-        getsubf_letter2 = substr(str, getsubf_i+1, 1);
-        if (getsubf_letter2 == getsubf_K_BD) {
-          getsubf_letter3 = substr(str, getsubf_i+2, 1);
-          if ((getsubf_letter3 >= getsubf_K_A0) &&
-              (getsubf_letter3 <  getsubf_K_C0)  ) {
-            getsubf_pos += 1;
-          } else {
-            getsubf_pos += 2;
-          }
-        } else if (getsubf_letter2 == getsubf_K_BE) {
-          getsubf_letter3 = substr(str, getsubf_i+2, 1);
-          if ((getsubf_letter3 >= getsubf_K_80) &&
-              (getsubf_letter3 <  getsubf_K_A0)  ) {
-            getsubf_pos += 1;
-          } else {
-            getsubf_pos += 2;
-          }
-        } else {
-          getsubf_pos += 2;
-        }
-      } else {
-        getsubf_pos += 2;
-      }
-      getsubf_i   += 3;
-    } else if (getsubf_letter < getsubf_F8_4) {
-      getsubf_i   += 4;
-      getsubf_pos += 2;
-    } else if (getsubf_letter < getsubf_FC_5) {
-      getsubf_i   += 5;
-      getsubf_pos += 2;
-    } else if (getsubf_letter < getsubf_FE_6) {
-      getsubf_i   += 6;
-      getsubf_pos += 2;
-    } else {
-      # invalid UTF-8 character
-      getsubf_i++;
+    l = substr(str, i, 1);
+    if        (l < chr_80_1) {i++; p++;
+    } else if (l < chr_C0_X) {i++; # invalid UTF-8
+    } else if (l < chr_E0_2) {i += 2; p += 2;
+    } else if (l < chr_F0_3) {
+      if (l == chr_K_EF) {
+        l2 = substr(str, i+1, 1);
+        if        (l2 == chr_K_BD) {
+          l3 = substr(str, i+2, 1);
+          if ((l3 >= chr_K_A0) && (l3 <  chr_K_C0)) {p += 1;
+          } else                                    {p += 2;}
+        } else if (l2 == chr_K_BE) {
+          l3 = substr(str, i+2, 1);
+          if ((l3 >= chr_K_80) && (l3 <  chr_K_A0)) {p += 1;
+          } else                                    {p += 2;}
+        } else                     {p += 2;                  }
+      } else             {p += 2;                             }
+      i   += 3;
+    } else if (l < chr_F8_4) {i += 4; p += 2;
+    } else if (l < chr_FC_5) {i += 5; p += 2;
+    } else if (l < chr_FE_6) {i += 6; p += 2;
+    } else                   {i++;                             } # invalid UTF-8
     }
-    if (getsubf_substr_s > 0) {
-      if ((startpos + len) == getsubf_pos) {
-        getsubf_substr_e = getsubf_i;
-        break;
-      } else if (len == 0) {
-        getsubf_substr_e = getsubf_substr_s;
-        break;
-      } else if ((startpos + len) < getsubf_pos) {
-        _assert_exit = 1;
-        exit _assert_exit;
-      }
+    if (st > 0) {
+      if        ((startpos + len) == p) {ed = i ; break;
+      } else if (len == 0)              {ed = st; break;
+      } else if ((startpos + len) <  p) {_assert_exit = 1; exit _assert_exit;}
     }
   }
-  if (getsubf_substr_s == 0) {
-    _assert_exit = 1;
-    exit _assert_exit;
-  }
-  return (getsubf_substr_e == 0)                                    \
-    ? substr(str,getsubf_substr_s)                                  \
-    : substr(str,getsubf_substr_s,getsubf_substr_e-getsubf_substr_s);
+  if (st == 0) {_assert_exit = 1; exit _assert_exit;}
+  return (ed == 0) ? substr(str,st) : substr(str,st,ed-st);
 }
 # generate the field cluster for the number and NF mixed arguments
 # with no substr part (e.g. 1/NF, NF/1, 3/NF-3)
-function getfldclstr1(fldnum1,fldnum2) {
-  getfldclstr1_ = $fldnum1;
+function getfldclstr1(fldnum1,fldnum2 ,i,str) {
+  str = $fldnum1;
   if (fldnum1 <= fldnum2) {
-    for (getfldclstr1_i=fldnum1+1;getfldclstr1_i<=fldnum2;getfldclstr1_i++) {
-      getfldclstr1_ = getfldclstr1_ FS $getfldclstr1_i;
+    for (i=fldnum1+1;i<=fldnum2;i++) {
+      str = str FS $i;
     }
   } else {
-    for (getfldclstr1_i=fldnum1-1;getfldclstr1_i>=fldnum2;getfldclstr1_i--) {
-      getfldclstr1_ = getfldclstr1_ FS $getfldclstr1_i;
+    for (i=fldnum1-1;i>=fldnum2;i--) {
+      str = str FS $i;
     }
   }
-  return getfldclstr1_;
+  return str;
 }
 # generate the field cluster for the number and NF mixed arguments
 # with a substr part (e.g. 1.1/NF, NF.3.6/1, 3.1.5/NF-3)
-function getfldclstr2(fldnum1, fldnum2, stpos, len) {
-  getfldclstr2_ = getsubf($fldnum1,stpos,len);
+function getfldclstr2(fldnum1, fldnum2, stpos, len  ,i,str) {
+  str = getsubf($fldnum1,stpos,len);
   if (fldnum1 <= fldnum2) {
-    for (getfldclstr2_i=fldnum1+1;getfldclstr2_i<=fldnum2;getfldclstr2_i++) {
-      getfldclstr2_ = getfldclstr2_ FS getsubf($getfldclstr2_i,stpos,len);
+    for (i=fldnum1+1;i<=fldnum2;i++) {
+      str = str FS getsubf($i,stpos,len);
     }
   } else {
-    for (getfldclstr2_i=fldnum1-1;getfldclstr2_i>=fldnum2;getfldclstr2_i--) {
-      getfldclstr2_ = getfldclstr2_ FS getsubf($getfldclstr2_i,stpos,len);
+    for (i=fldnum1-1;i>=fldnum2;i--) {
+      str = str FS getsubf($i,stpos,len);
     }
   }
-  return getfldclstr2_;
+  return str;
 }
 '
 if [ $directmode -ne 0 ]; then
-  printf '%s' "$directstr" | env -i awk "$awkcode"
+  printf '%s' "$directstr" | awk "$awkcode"
 else
-  exec env -i awk "$awkcode" "$file"
+  exec awk "$awkcode" "$file"
 fi
