cgi-name,cjoin0,cjoin1,delf,gyo,self,keycut,han,calclock,comma,count,ctail,getfirst,getlast,cjoin2,mime-read,zen,sorter:improved

diff --git a/COMMANDS.SH/han b/COMMANDS.SH/han
--- a/COMMANDS.SH/han
+++ b/COMMANDS.SH/han
@@ -8,14 +8,18 @@ print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [+<n>h] <f1> <f2> ... <file>
 	        : ${0##*/} -d <string>
-	Version : Sun Nov 23 04:06:08 JST 2014
+	Version : Wed Jun 17 22:40:23 JST 2015
 	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
 __USAGE
   exit 1
 }
 
 # initialize
+set -u
+umask 0022
 PATH='/usr/bin:/bin'
+IFS=$(printf ' \t\n_'); IFS=${IFS%_}
+export IFS LANG=C LC_ALL=C PATH
 directmode=0
 directstr=''
 awkc0=''
@@ -41,7 +45,7 @@ for arg in "$@"; do
     directmode=1
     continue
   elif [ \( $opt_part -ne 0 \) -a \( "_$arg" != "_${arg#+}" \) ]; then
-    s=$(echo "_$arg" | sed 's/^_+\([0-9]*\)h$/\1/')
+    s=$(printf '%s\n' "$arg" | sed 's/^+\([0-9]*\)h$/\1/')
     [ "_$s" != "_$arg" ] || print_usage_and_exit
     [ -z "$s"          ] && { hopt=1; continue; }
     hopt=$(expr $s + 0)
@@ -66,12 +70,12 @@ for arg in "$@"; do
   # check both
   j=0
   for s in $arg1 $arg2; do
-    if echo "_$s" | grep '^_[0-9]\{1,\}$' > /dev/null; then
+    if printf '%s\n' "$s" | grep -q '^[0-9]\{1,\}$'; then
       j=$((j+1))
       if [ "$s" -eq 0 ]; then
         all_fields=1
       fi
-    elif echo "_$s" | grep -E '^_(NF|NF-[0-9]+)$' > /dev/null; then
+    elif printf '%s\n' "$s" | grep -Eq '^(NF|NF-[0-9]+)$'; then
       j=$((j+1))
     fi
   done
@@ -108,10 +112,11 @@ else
   then
     print_usage_and_exit
   elif [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
-    echo "${0##*/}: Cannot open the file" 1>&2
+    printf '%s: Cannot open the file\n' "${0##*/}" 1>&2
     exit 1
   fi
 fi
+case "$file" in ''|-|/*|./*|../*) :;; *) file="./$file";; esac
 
 # make the part of the awk code
 if [ $all_fields -eq 0 ]; then
@@ -234,12 +239,11 @@ if [ $all_fields -eq 0 ]; then
               printf("convert_marked_flds();print;");
             }
           '                                         )
-  echo "$awkc0" | grep 'NF' >/dev/null
-  if [ $? -ne 0 ]; then
+  if echo "$awkc0" | grep -q 'NF'; then
+    awkc0b=''
+  else
     awkc0b=${awkc0%convert_marked_flds*}
     awkc0='convert_marked_flds();print;'
-  else
-    awkc0b=''
   fi
 else
   awkc0='print utf8zen2han($0);'
