keta,mojihame*:improved

diff --git a/COMMANDS.SH/keta b/COMMANDS.SH/keta
--- a/COMMANDS.SH/keta
+++ b/COMMANDS.SH/keta
@@ -9,23 +9,89 @@ print_usage_and_exit () {
 	Usage   : ${0##*/} n1 n2 .. <filename>
 	        : ${0##*/} -v <filename>
 	        : ${0##*/} [--] <filename>
-	Version : Tue Oct 14 18:07:54 JST 2014
+	Version : Thu Jun 18 01:26:32 JST 2015
 	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
 __USAGE
   exit 1
 }
-# the alternative of the mktemp command
-which mktemp >/dev/null 2>&1 || {
-  mktemp_fileno=0
-  mktemp() {
-    (
-      mktemp_filename="/tmp/${0##*/}.$$.$mktemp_fileno"
-      mktemp_fileno=$((mktemp_fileno+1))
-      touch "$mktemp_filename"
-      chmod 600 "$mktemp_filename"
-      echo "$mktemp_filename"
-    )
+# the alternative of the "mktemp -t"
+mktempf0() {
+  # --- parameters, etc. ---------------------------------------------
+  num_of_digits=16  # Length of Random String
+  n=10              # Max Times of Retrying
+  chrs='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_'
+                    # Available letters
+  LF=$(printf '\\\n_');LF=${LF%_}
+  # --- call built-in mktemp if exists -------------------------------
+  type mktemp >/dev/null 2>&1 && {
+    mktemp -t tmp.${0##*/}.$$.XXXXXXXXXXXXXXXX
+    return $?
   }
+  # --- set the temporary directory ----------------------------------
+  Dir_tmp=$(set | grep -q ^TMPDIR= | sed 's/^[^=]\{1,\}=//');
+  case "$Dir_tmp" in
+    '') Dir_tmp='/tmp'      ;;
+    /)  Dir_tmp=''          ;;
+    *)  Dir_tmp=${Dir_tmp%/};;
+  esac
+  # --- mktemp loop --------------------------------------------------
+  while [ $n -ge 0 ]; do
+    # --- Generate Ramdom string -------------------------------------
+    # calculate the number of words which required
+    nw=$(echo "${num_of_digits}*l(${#chrs})/11.09+1" | # 11.09=ln(65536)
+         bc -l                                       |
+         sed 's/\..*$//'                             )
+    # make a random hexadecimal digit
+    if [ -c /dev/urandom ]; then
+      hstr=$(dd if=/dev/urandom bs=2 count=$nw 2>/dev/null |
+             od -A n -t x2 -v                              |
+             tr 'abcdef ' 'ABCDEF\n'                       |
+             tr -Cd 0123456789ABCDEF                       )
+    else
+      hstr=$( (ps -Ao pid,etime,pcpu,vsz; date)         |
+             od -t d4 -A n -v                           |
+             sed 's/[^0-9]\{1,\}/'"$LF"'/g'             |
+             grep '[0-9]'                               |
+             tail -n 42                                 |
+             sed 's/.*\(.\{8\}\)$/\1/g'                 |
+             awk 'BEGIN{a=-2147483648;}                 #
+                       {a+=$1;        }                 #
+                  END  {                                #
+                    srand(a);                           #
+                    for(i=0;i<'$nw';i++){               #
+                      printf("%02X",int(rand()*65536)); #
+                    }                                   #
+                  }'                                    )
+    fi
+    # make a random string from the hexadecimal digit
+    s=$(echo "obase=${#chrs};ibase=16;$hstr"                     |
+        bc                                                       |
+        tr -d '\\\n'                                             |
+        tr ' ' '\n'                                              |
+        awk 'BEGIN  {for(i=1;i<'$num_of_digits';i++){print 0;}}  #
+             /[0-9]/{print;                                   }' |
+        awk 'BEGIN  {ORS="";                                     #
+                     s="'"$chrs"'";                              #
+                     for(i=0;i<length(s);i++){                   #
+                       c[i]=substr(s,i+1,1);                     #
+                     }                        }                  #
+             /[0-9]/{print c[$0*1];           }'                 |
+        tail -c $num_of_digits                                   )
+    # --- Making the file path ---------------------------------------
+    Path_target="${Dir_tmp}/tmp.${0##*/}.$$.$s"
+    # --- Making the file --------------------------------------------
+    (set -C; umask 177; : > "$Path_target") 2>/dev/null || {
+      [ -f "$Path_target" ] && { n=$((n-1)); continue; }
+      n=-1; break;
+    }
+    break
+  done
+  # --- print error message when failed to make a file ---------------
+  case "$n" in -1) return 1;; esac
+  # --- print the path of the file -----------------------------------
+  printf '%s\n' "$Path_target"
+  # --- return successfully ------------------------------------------
+  return 0
 }
 # decide whether to use the alternative length of AWK or not
 if awk 'BEGIN{a[1]=1;b=length(a)}' 2>/dev/null; then
@@ -36,7 +102,11 @@ fi
 
 
 # initialize
+set -u
+umask 0022
 PATH='/usr/bin:/bin'
+IFS=$(printf ' \t\n_'); IFS=${IFS%_}
+export IFS LANG=C LC_ALL=C PATH
 widthes=''
 left_justification=0
 verbose=0
@@ -49,23 +119,23 @@ mode=0 # 0 ... count the max-widthes of all fields & auto-right-justification
        # 3 ... count the max-widthes of all fields & print them
 
 # parse the arguments
-case "$1" in
+case "${1:-}" in
   --)
     left_justification=1
     mode=2
     shift
-    lastarg=$1
+    lastarg=${1:-}
     ;;
   -v)
     verbose=1
     mode=3
     shift
-    lastarg=$1
+    lastarg=${1:-}
     ;;
 esac
 if [ $mode -eq 0 ]; then
   while [ $# -gt 0 ]; do
-    test=$(echo "_$1" | grep -E '^_-?[0-9]+(x([0-9]+|NF(-[0-9]+)?))?$')
+    test=$(printf '%s\n' "$1" | grep -E '^-?[0-9]+(x([0-9]+|NF(-[0-9]+)?))?$')
     if [ -n "$test" ]; then
       mode=1
       widthes="$widthes ${test#_}"
@@ -78,7 +148,7 @@ if [ $mode -eq 0 ]; then
 fi
 if [ $# -gt 1 ]; then
   print_usage_and_exit
-elif [ -z "$1" ]; then
+elif [ -z "${1:-}" ]; then
   file='-'
 elif [ \( -f "$1" \) -o \( -c "$1" \) -o \( -p "$1" \) -o \
        \( "_$1" = '_-' \)                                 ]; then
@@ -87,7 +157,7 @@ else
   print_usage_and_exit
 fi
 if [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
-  echo "${0##*/}: Cannot open the file" 1>&2
+  printf '%s: Cannot open the file\n' "${0##*/}" 1>&2
   exit 1
 fi
 
@@ -104,81 +174,66 @@ then
 fi
 if [ \( $readonce -ne 0 \) -a \( \( $mode -eq 0 \) -o \( $mode -eq 2 \) \) ]
 then
-  tmpfile=$(mktemp -t "${0##*/}.XXXXXXXX")
+  tmpfile=$(mktempf0)
   if [ $? -eq 0 ]; then
     trap "rm -f $tmpfile; exit" EXIT HUP INT QUIT PIPE ALRM TERM
     cat > "$tmpfile"
     file=$tmpfile
   else
-    echo "${0##*/}: Cannot create a temporary file" 1>&2
+    printf '%s: Cannot create a temporary file\n' "${0##*/}" 1>&2
     exit 1
   fi
 fi
+case "$file" in ''|-|/*|./*|../*) :;; *) file="./$file";; esac
 
 
 # awkcode : get the length of the UTF-8 string (it is not a byte number)
 awkcode_func_utf8strlen='
 # strlen for UTF-8 (preparation : you must call this before using utf8strlen)
-function utf8strlen_prep() {
-  utf8strlen_80_1 = sprintf("\200");
-  utf8strlen_C0_X = sprintf("\300");
-  utf8strlen_E0_2 = sprintf("\340");
-  utf8strlen_F0_3 = sprintf("\360");
-  utf8strlen_F8_4 = sprintf("\370");
-  utf8strlen_FC_5 = sprintf("\374");
-  utf8strlen_FE_6 = sprintf("\376");
-  utf8strlen_K_EF = sprintf("\357");
-  utf8strlen_K_BD = sprintf("\275");
-  utf8strlen_K_BE = sprintf("\276");
-  utf8strlen_K_A0 = sprintf("\240");
-  utf8strlen_K_C0 = sprintf("\300");
-  utf8strlen_K_80 = sprintf("\200");
+function utf8_prep() {
+  chr_80_1 = sprintf("\200");
+  chr_C0_X = sprintf("\300");
+  chr_E0_2 = sprintf("\340");
+  chr_F0_3 = sprintf("\360");
+  chr_F8_4 = sprintf("\370");
+  chr_FC_5 = sprintf("\374");
+  chr_FE_6 = sprintf("\376");
+  chr_K_EF = sprintf("\357");
+  chr_K_BD = sprintf("\275");
+  chr_K_BE = sprintf("\276");
+  chr_K_A0 = sprintf("\240");
+  chr_K_C0 = sprintf("\300");
+  chr_K_80 = sprintf("\200");
 }
 
 # strlen for UTF-8 (main)
-function utf8strlen(str) {
-  utf8strlen_ = 0;
-  for (utf8strlen_i = 1; utf8strlen_i <= length(str); utf8strlen_i++) {
-    utf8strlen_++;
-    utf8strlen_letter=substr(str, utf8strlen_i, 1);
-    if (utf8strlen_letter < utf8strlen_80_1) {
-      continue;
-    } else if (utf8strlen_letter < utf8strlen_C0_X) {
-      utf8strlen_--;
-      continue;
-    } else if (utf8strlen_letter < utf8strlen_E0_2) {
-      utf8strlen_i++;
-    } else if (utf8strlen_letter < utf8strlen_F0_3) {
-      if (utf8strlen_letter == utf8strlen_K_EF) {
-        utf8strlen_letter2 = substr(str, utf8strlen_i+1, 1);
-        if (utf8strlen_letter2 == utf8strlen_K_BD) {
-          utf8strlen_letter3 = substr(str, utf8strlen_i+2, 1);
-          if ((utf8strlen_letter3 >= utf8strlen_K_A0) &&
-              (utf8strlen_letter3 <  utf8strlen_K_C0)  ) {
-            utf8strlen_--;
-          }
-        } else if (utf8strlen_letter2 == utf8strlen_K_BE) {
-          utf8strlen_letter3 = substr(str, utf8strlen_i+2, 1);
-          if ((utf8strlen_letter3 >= utf8strlen_K_80) &&
-              (utf8strlen_letter3 <  utf8strlen_K_A0)  ) {
-            utf8strlen_--;
-          }
+function utf8strlen(str, len,i,l1,l2,l3) {
+  len = 0;
+  for (i = 1; i <= length(str); i++) {
+    len++;
+    l1=substr(str, i, 1);
+    if      (l1 < chr_80_1)   {       continue;
+    } else if (l1 < chr_C0_X) {len--; continue;
+    } else if (l1 < chr_E0_2) {i++;
+    } else if (l1 < chr_F0_3) {
+      if (l1 == chr_K_EF) {
+        l2 = substr(str, i+1, 1);
+        if (l2 == chr_K_BD) {
+          l3 = substr(str, i+2, 1);
+          if ((l3 >= chr_K_A0) && (l3 < chr_K_C0)) {len--;}
+        } else if (l2 == chr_K_BE) {
+          l3 = substr(str, i+2, 1);
+          if ((l3 >= chr_K_80) && (l3 < chr_K_A0)) {len--;}
         }
       }
-      utf8strlen_i += 2;
-    } else if (utf8strlen_letter < utf8strlen_F8_4) {
-      utf8strlen_i += 3;
-    } else if (utf8strlen_letter < utf8strlen_FC_5) {
-      utf8strlen_i += 4;
-    } else if (utf8strlen_letter < utf8strlen_FE_6) {
-      utf8strlen_i += 5;
-    } else {
-      utf8strlen_--;
-      continue;
-    }
-    utf8strlen_++;
+      i += 2;
+    } else if (l1 < chr_F8_4) {i += 3;
+    } else if (l1 < chr_FC_5) {i += 4;
+    } else if (l1 < chr_FE_6) {i += 5;
+    } else                    {len--;  continue;}
+    len++;
   }
-  return utf8strlen_;
+  return len;
 }
 '
 
@@ -188,7 +243,7 @@ if [ \( $mode -eq 0 \) -o \( $mode -eq 2 \) -o \( $mode -eq 3 \) ]; then
 
 awkcode_main_width_counter='
 BEGIN {
-  utf8strlen_prep();
+  utf8_prep();
   max_nf = 0;
 }
 
@@ -223,7 +278,7 @@ END {
   print substr(widthes, 1, length(widthes) - 1);
 }
 '
-widthes=$(env -i awk "$awkcode_main_width_counter$awkcode_func_utf8strlen" "$file")
+widthes=$(awk "$awkcode_main_width_counter$awkcode_func_utf8strlen" "$file")
 
 fi
 
@@ -249,7 +304,7 @@ awkcode_main_justificator='
 function arlen(ar,i,l){for(i in ar){l++;}return l;}
 
 BEGIN {
-  utf8strlen_prep();
+  utf8_prep();
   split(widthes_str, width_str);
   varriable_widthes = (match(widthes_str, /NF/)) ? 1 : 0;
   if (!varriable_widthes) {
@@ -292,56 +347,57 @@ BEGIN {
   print substr(line, 1, length(line)-length(FS));
 }
 
-function decide_widthes() {
-  for (decide_widthes_j in width) {
-    delete width[decide_widthes_j];
-  }
-  decide_widthes_j = 0;
-  for (decide_widthes_i = 1; decide_widthes_i <= '$arlen'(width_str); decide_widthes_i++) {
-    if (match(width_str[decide_widthes_i], /^-?[0-9]+$/)) {
-      decide_widthes_j++;
-      width[decide_widthes_j] = width_str[decide_widthes_i];
+function decide_widthes(   mode,i,j,k,n,s) {
+  split("", width);
+  j = 0;
+  for (i = 1; i <= '$arlen'(width_str); i++) {
+    if (match(width_str[i], /^-?[0-9]+$/)) {
+      j++;
+      width[j] = width_str[i];
       continue;
     }
-    if (match(width_str[decide_widthes_i], /^-?[0-9]+x[0-9]+$/)) {
-      decide_widthes_multmode = 1;
-    } else if (match(width_str[decide_widthes_i], /^-?[0-9]+xNF$/)) {
-      decide_widthes_multmode = 2;
-    } else if (match(width_str[decide_widthes_i], /^-?[0-9]+xNF-[0-9]+$/)) {
-      decide_widthes_multmode = 3;
+    if (match(width_str[i], /^-?[0-9]+x[0-9]+$/)) {
+      mode = 1;
+    } else if (match(width_str[i], /^-?[0-9]+xNF$/)) {
+      mode = 2;
+    } else if (match(width_str[i], /^-?[0-9]+xNF-[0-9]+$/)) {
+      mode = 3;
     } else {
       continue;
     }
-    match(width_str[decide_widthes_i], /^-?[0-9]+/);
-    decide_widthes_str = substr(width_str[decide_widthes_i], RSTART, RLENGTH);
-    if (decide_widthes_multmode == 1) {
-      match(width_str[decide_widthes_i], /[0-9]+$/);
-      decide_widthes_n = substr(width_str[decide_widthes_i], RSTART, RLENGTH) + 0;
-      for (decide_widthes_k = 0; decide_widthes_k < decide_widthes_n; decide_widthes_k++) {
-        decide_widthes_j++;
-        width[decide_widthes_j] = decide_widthes_str;
+    match(width_str[i], /^-?[0-9]+/);
+    s = substr(width_str[i], RSTART, RLENGTH);
+    if (mode == 1) {
+      match(width_str[i], /[0-9]+$/);
+      n = substr(width_str[i], RSTART, RLENGTH) + 0;
+      for (k = 0; k < n; k++) {
+        j++;
+        width[j] = s;
       }
-    } else if (decide_widthes_multmode == 2) {
-      decide_widthes_n = NF;
-      for (decide_widthes_k = 0; decide_widthes_k < decide_widthes_n; decide_widthes_k++) {
-        decide_widthes_j++;
-        width[decide_widthes_j] = decide_widthes_str;
+    } else if (mode == 2) {
+      n = NF;
+      for (k = 0; k < n; k++) {
+        j++;
+        width[j] = s;
       }
-    } else if (decide_widthes_multmode == 3) {
-      match(width_str[decide_widthes_i], /[0-9]+$/);
-      decide_widthes_n = NF - substr(width_str[decide_widthes_i], RSTART, RLENGTH);
-      for (decide_widthes_k = 0; decide_widthes_k < decide_widthes_n; decide_widthes_k++) {
-        decide_widthes_j++;
-        width[decide_widthes_j] = decide_widthes_str;
+    } else if (mode == 3) {
+      match(width_str[i], /[0-9]+$/);
+      n = NF - substr(width_str[i], RSTART, RLENGTH);
+      for (k = 0; k < n; k++) {
+        j++;
+        width[j] = s;
       }
     }
   }
 }
 '
 if [ -z "$tmpfile" ]; then
-  exec env -i awk -v "widthes_str=$widthes" "$awkcode_main_justificator$awkcode_func_utf8strlen" "$file"
+  exec awk -v "widthes_str=$widthes"                                       \
+              "$awkcode_main_justificator$awkcode_func_utf8strlen" "$file"
 else
-  env -i awk -v "widthes_str=$widthes" "$awkcode_main_justificator$awkcode_func_utf8strlen" "$file"
+# (commands should not be run with "exec" because of having to remove tempfile)
+       awk -v "widthes_str=$widthes"                                       \
+              "$awkcode_main_justificator$awkcode_func_utf8strlen" "$file"
 fi
 
 fi
diff --git a/COMMANDS.SH/mojihame b/COMMANDS.SH/mojihame
--- a/COMMANDS.SH/mojihame
+++ b/COMMANDS.SH/mojihame
@@ -9,14 +9,18 @@ print_usage_and_exit () {
 		Usage   : ${0##*/} [-d[<string>]] <template> <data>
 		        : ${0##*/} -l<label> [-d[<string>]] <template> <data>
 		        : ${0##*/} -h<label> [-d[<string>]] <template> <data>
-		Version : Fri Apr 11 15:52:47 JST 2014
+		Version : Thu Jun 18 23:25:33 JST 2015
 		        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
 __USAGE
   exit 1
 }
 
 # Initialize
+set -u
+umask 0022
 PATH='/usr/bin:/bin'
+IFS=$(printf ' \t\n_'); IFS=${IFS%_}
+export IFS LANG=C LC_ALL=C PATH
 
 # parse the arguments
 mode='p' # "p" (default) or "r" or "l" or "h"
@@ -81,13 +85,15 @@ for file in "$file_tmpl" "$file_data"; do
 done
 [ $use_stdin -le 1 ] || print_usage_and_exit
 if [ \( ! -r "$file_tmpl" \) -a \( "_$file_tmpl" != '_-' \) ]; then
-  echo "${0##*/}: Cannot open the template file" 1>&2
+  printf '%s: Cannot open the template file\n' "${0##*/}" 1>&2
   exit 1
 fi
 if [ \( ! -r "$file_data" \) -a \( "_$file_data" != '_-' \) ]; then
-  echo "${0##*/}: Cannot open the data file" 1>&2
+  printf '%s: Cannot open the data file\n' "${0##*/}" 1>&2
   exit 1
 fi
+case "$file_tmpl" in ''|-|/*|./*|../*) :;; *) file="./$file_tmpl";; esac
+case "$file_data" in ''|-|/*|./*|../*) :;; *) file="./$file_data";; esac
 
 # main
 case $mode in
diff --git a/COMMANDS.SH/mojihame-h b/COMMANDS.SH/mojihame-h
--- a/COMMANDS.SH/mojihame-h
+++ b/COMMANDS.SH/mojihame-h
@@ -7,7 +7,7 @@
 print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 		Usage   : ${0##*/} -h<label> [-d[<string>]] <template> <data>
-		Version : Sat Jun 28 13:58:20 JST 2014
+		Version : Thu Jun 18 23:28:20 JST 2015
 		        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
 __USAGE
   exit 1
@@ -20,7 +20,11 @@ else
 fi
 
 # Initialize
+set -u
+umask 0022
 PATH='/usr/bin:/bin'
+IFS=$(printf ' \t\n_'); IFS=${IFS%_}
+export IFS LANG=C LC_ALL=C PATH
 
 # parse the arguments
 label=''
@@ -75,13 +79,15 @@ for file in "$file_tmpl" "$file_data"; do
 done
 [ $use_stdin -le 1 ] || print_usage_and_exit
 if [ \( ! -r "$file_tmpl" \) -a \( "_$file_tmpl" != '_-' \) ]; then
-  echo "${0##*/}: Cannot open the template file" 1>&2
+  printf '%s: Cannot open the template file\n' "${0##*/}" 1>&2
   exit 1
 fi
 if [ \( ! -r "$file_data" \) -a \( "_$file_data" != '_-' \) ]; then
-  echo "${0##*/}: Cannot open the data file" 1>&2
+  printf '%s: Cannot open the data file\n' "${0##*/}" 1>&2
   exit 1
 fi
+case "$file_tmpl" in ''|-|/*|./*|../*) :;; *) file="./$file_tmpl";; esac
+case "$file_data" in ''|-|/*|./*|../*) :;; *) file="./$file_data";; esac
 
 # main
 export v1=$file_tmpl
@@ -97,6 +103,8 @@ BEGIN {
   OFS="";
   ORS="";
   TAB = sprintf("\t");
+  TABn= sprintf("\tn");
+  TABt= sprintf("\tt");
   LF  = sprintf("\n");
   file_tmpl = (ENVIRON["v1"]!="-") ? ENVIRON["v1"] : "/dev/stdin";
   label     = ENVIRON["v2"];
@@ -141,9 +149,15 @@ BEGIN {
       if (s == asnull) {
         s = "";
       } else {
-        gsub(/\\_/, TAB, s);
-        gsub(/_/  , " ", s);
-        gsub(/\t/ , "_", s);
+        gsub(/\\\\/, LF  , s); # The Rule of Premutation
+        gsub(/\\_/ , TAB , s); # -----------------------
+        gsub(/_/   , " " , s); #   "_"    ->   " "
+        gsub(/\t/  , "_" , s); #   "\_"   ->   "_"
+        gsub(/\\t/ , TABt, s); #
+        gsub(/\\n/ , TABn, s); #
+        gsub(/\n/  , "\\", s); #   "\\"   ->   "\"
+        gsub(/\tn/ , LF  , s); #   "\n"   ->   "<LF>"
+        gsub(/\tt/ , TAB , s); #   "\t"   ->   "<TAB>"
       }
       data_buf_odd[i] = s;
     }
@@ -160,9 +174,15 @@ BEGIN {
         if (s == asnull) {
           s = "";
         } else {
-          gsub(/\\_/, TAB, s);
-          gsub(/_/  , " ", s);
-          gsub(/\t/ , "_", s);
+          gsub(/\\\\/, LF  , s); # The Rule of Premutation
+          gsub(/\\_/ , TAB , s); # -----------------------
+          gsub(/_/   , " " , s); #   "_"    ->   " "
+          gsub(/\t/  , "_" , s); #   "\_"   ->   "_"
+          gsub(/\\t/ , TABt, s); #
+          gsub(/\\n/ , TABn, s); #
+          gsub(/\n/  , "\\", s); #   "\\"   ->   "\"
+          gsub(/\tn/ , LF  , s); #   "\n"   ->   "<LF>"
+          gsub(/\tt/ , TAB , s); #   "\t"   ->   "<TAB>"
         }
         data_buf_odd[i] = s;
       }
@@ -181,9 +201,15 @@ BEGIN {
         if (s == asnull) {
           s = "";
         } else {
-          gsub(/\\_/, TAB, s);
-          gsub(/_/  , " ", s);
-          gsub(/\t/ , "_", s);
+          gsub(/\\\\/, LF  , s); # The Rule of Premutation
+          gsub(/\\_/ , TAB , s); # -----------------------
+          gsub(/_/   , " " , s); #   "_"    ->   " "
+          gsub(/\t/  , "_" , s); #   "\_"   ->   "_"
+          gsub(/\\t/ , TABt, s); #
+          gsub(/\\n/ , TABn, s); #
+          gsub(/\n/  , "\\", s); #   "\\"   ->   "\"
+          gsub(/\tn/ , LF  , s); #   "\n"   ->   "<LF>"
+          gsub(/\tt/ , TAB , s); #   "\t"   ->   "<TAB>"
         }
         data_buf_even[i] = s;
       }
diff --git a/COMMANDS.SH/mojihame-l b/COMMANDS.SH/mojihame-l
--- a/COMMANDS.SH/mojihame-l
+++ b/COMMANDS.SH/mojihame-l
@@ -7,7 +7,7 @@
 print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 		Usage   : ${0##*/} [-l<label>] [-d[<string>]] <template> <data>
-		Version : Sat Jun 28 14:07:26 JST 2014
+		Version : Thu Jun 18 23:29:39 JST 2015
 		        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
 __USAGE
   exit 1
@@ -20,7 +20,11 @@ else
 fi
 
 # Initialize
+set -u
+umask 0022
 PATH='/usr/bin:/bin'
+IFS=$(printf ' \t\n_'); IFS=${IFS%_}
+export IFS LANG=C LC_ALL=C PATH
 
 # parse the arguments
 label=''
@@ -74,13 +78,15 @@ for file in "$file_tmpl" "$file_data"; do
 done
 [ $use_stdin -le 1 ] || print_usage_and_exit
 if [ \( ! -r "$file_tmpl" \) -a \( "_$file_tmpl" != '_-' \) ]; then
-  echo "${0##*/}: Cannot open the template file" 1>&2
+  printf '%s: Cannot open the template file\n' "${0##*/}" 1>&2
   exit 1
 fi
 if [ \( ! -r "$file_data" \) -a \( "_$file_data" != '_-' \) ]; then
-  echo "${0##*/}: Cannot open the data file" 1>&2
+  printf '%s: Cannot open the data file\n' "${0##*/}" 1>&2
   exit 1
 fi
+case "$file_tmpl" in ''|-|/*|./*|../*) :;; *) file="./$file_tmpl";; esac
+case "$file_data" in ''|-|/*|./*|../*) :;; *) file="./$file_data";; esac
 
 # main
 export v1=$file_tmpl
@@ -96,6 +102,8 @@ BEGIN {
   OFS="";
   ORS="";
   TAB = sprintf("\t");
+  TABn= sprintf("\tn");
+  TABt= sprintf("\tt");
   LF  = sprintf("\n");
   file_tmpl = (ENVIRON["v1"]!="-") ? ENVIRON["v1"] : "/dev/stdin";
   label     = ENVIRON["v2"];
@@ -127,9 +135,15 @@ BEGIN {
       if (s == asnull) {
         s = "";
       } else {
-        gsub(/\\_/, TAB, s);
-        gsub(/_/  , " ", s);
-        gsub(/\t/ , "_", s);
+        gsub(/\\\\/, LF  , s); # The Rule of Premutation
+        gsub(/\\_/ , TAB , s); # -----------------------
+        gsub(/_/   , " " , s); #   "_"    ->   " "
+        gsub(/\t/  , "_" , s); #   "\_"   ->   "_"
+        gsub(/\\t/ , TABt, s); #
+        gsub(/\\n/ , TABn, s); #
+        gsub(/\n/  , "\\", s); #   "\\"   ->   "\"
+        gsub(/\tn/ , LF  , s); #   "\n"   ->   "<LF>"
+        gsub(/\tt/ , TAB , s); #   "\t"   ->   "<TAB>"
       }
       data_buf[i] = s;
     }
