nameread,plus,retu,sm2,tarr,tateyoko,yarr:improved

diff --git a/COMMANDS.SH/nameread b/COMMANDS.SH/nameread
--- a/COMMANDS.SH/nameread
+++ b/COMMANDS.SH/nameread
@@ -7,14 +7,18 @@
 print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [-el] [-d<c>] [-i<string>] <name> <name_file>
-	Version : Fri Jun 27 03:03:38 JST 2014
+	Version : Sat Jun 20 00:25:35 JST 2015
 	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
 __USAGE
   exit 1
 }
 
 # initialize
+set -u
+umask 0022
 PATH='/usr/bin:/bin'
+IFS=$(printf ' \t\n_'); IFS=${IFS%_}
+export IFS LANG=C LC_ALL=C PATH
 dopt=''
 dopt_is_set=0
 iopt=''
@@ -22,6 +26,7 @@ eopt_is_set=0
 lopt_is_set=0
 name=''
 name_file=''
+TAB=$(printf '\t')
 
 # parse arguments
 [ $# -ge 1 ] || print_usage_and_exit
@@ -113,9 +118,10 @@ then
   print_usage_and_exit
 fi
 if [ \( ! -r "$name_file" \) -a \( "_$name_file" != '_-' \) ]; then
-  echo "${0##*/}: Cannot open the file" 1>&2
+  printf '%s: Cannot open the file\n' "${0##*/}" 1>&2
   exit 1
 fi
+case "$name_file" in ''|-|/*|./*|../*) :;; *) file="./$name_file";; esac
 
 #
 awk_code='
@@ -161,12 +167,12 @@ if [ $eopt_is_set -eq 0 ]; then
   exec awk "$awk_code" "$name_file"
 else
   if [ "_${name#^}" = "_$name" ]; then
-    name="[^[:blank:]]*${name}"
+    name="[^$TAB ]*${name}"
   else
     name="${name#^}"
   fi
   if [ "_${name%$}" = "_$name" ]; then
-    name="${name}[^[:blank:]]*"
+    name="${name}[^$TAB ]*"
   else
     name="${name%$}"
   fi
@@ -176,6 +182,6 @@ else
   export v4=$dopt_is_set
   export v5=$lopt_is_set
   export v6=$eopt_is_set
-  grep -E "^${name}([[:blank:]]+.*|)$" "$name_file" |
+  grep -E "^${name}([$TAB ]+.*|)\$" "$name_file" |
   exec awk "$awk_code"
 fi
diff --git a/COMMANDS.SH/retu b/COMMANDS.SH/retu
--- a/COMMANDS.SH/retu
+++ b/COMMANDS.SH/retu
@@ -7,7 +7,7 @@
 print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [-f] <file> ...
-	Version : Fri Apr 11 12:32:45 JST 2014
+	Version : Sat Jun 20 01:23:16 JST 2015
 	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
 __USAGE
   exit 1
@@ -15,7 +15,11 @@ __USAGE
 
 
 # initialize
+set -u
+umask 0022
 PATH='/usr/bin:/bin'
+IFS=$(printf ' \t\n_'); IFS=${IFS%_}
+export IFS LANG=C LC_ALL=C PATH
 foption=0
 file=''
 use_stdin=0
@@ -24,7 +28,8 @@ use_stdin=0
 
 awkcode_main='
 BEGIN {
-  last_nf = 0;
+  last_nf  = 0;
+  filename = ENVIRON["filename"];
 }
 
 {
@@ -60,18 +65,18 @@ for arg in "$@"; do
     print_usage_and_exit
   fi
   if [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
-    echo "${0##*/}: Cannot open the file \"$arg\"" 1>&2
+    printf '%s: Cannot open the file "%s"\n' "${0##*/}" "$arg" 1>&2
     exit 1
   fi
+  case "$file" in ''|-|/*|./*|../*) :;; *) file="./$file";; esac
   if [ $foption -ne 0 ]; then
-    filename=$arg
+    filename=$arg awk "$awkcode_main" "$file"
   else
-    filename=''
+    filename=''   awk "$awkcode_main" "$file"
   fi
-  awk -v "filename=$filename" "$awkcode_main" "$file"
 done
-if [ \( -z "$file" \) -a \( $foption -ne 0 \) ]; then
-  awk -v 'filename=-' "$awkcode_main"
+if   [ \( -z "$file" \) -a \( $foption -ne 0 \) ]; then
+  filename='-' awk "$awkcode_main"
 elif [ \( -z "$file" \) -a \( $foption -eq 0 \) ]; then
-  awk -v 'filename=' "$awkcode_main"
+  filename=''  awk "$awkcode_main"
 fi
diff --git a/COMMANDS.SH/sm2 b/COMMANDS.SH/sm2
--- a/COMMANDS.SH/sm2
+++ b/COMMANDS.SH/sm2
@@ -7,7 +7,7 @@
 print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [+count] <k1> <k2> <s1> <s2> <file>
-	Version : Fri Jun 27 01:24:27 JST 2014
+	Version : Sat Jun 20 23:30:41 JST 2015
 	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
 __USAGE
   exit 1
@@ -15,100 +15,123 @@ __USAGE
 
 
 # initialize
+set -u
+umask 0022
 PATH='/usr/bin:/bin'
+IFS=$(printf ' \t\n_'); IFS=${IFS%_}
+export IFS LANG=C LC_ALL=C PATH
 count=0
+k1=''; k2=''; s1=''; s2=''
 file=''
 
-
 # parse the arguments
-if [ "_$1" = "_+count" ]; then
-  count=1
-  shift
-fi
-
-[ $# -lt 4 ] && print_usage_and_exit
-
-echo "_$1" | grep '^_[0-9]\{1,\}$' >/dev/null || print_usage_and_exit
-echo "_$2" | grep '^_[0-9]\{1,\}$' >/dev/null || print_usage_and_exit
-echo "_$3" | grep '^_[0-9]\{1,\}$' >/dev/null || print_usage_and_exit
-echo "_$4" | grep '^_[0-9]\{1,\}$' >/dev/null || print_usage_and_exit
-[ \( $1 -gt $2 \) ] && print_usage_and_exit
-[ \( $3 -gt $4 \) -o \( $3 -le $2 \) ] && print_usage_and_exit
-if [ $1 -gt 0 ]; then
-  keyfileds=$(awk -v s=$1 -v e=$2 'BEGIN{for(i=s;i<=e;i++){printf("$%d",i)}}' |
-              sed 's/\([0-9]\)\$/\1 FS $/g'                                   )
-elif [ $2 -eq 0 ]; then
-  keyfileds='""'
+case "$1" in '+count') count=1;shift       ;; esac
+case $#   in   [0123]) print_usage_and_exit;; esac
+printf '%s' "$1" | grep -Eq '^([0-9]+|NF(-[0-9]+)?)$' || print_usage_and_exit
+printf '%s' "$2" | grep -Eq '^([0-9]+|NF(-[0-9]+)?)$' || print_usage_and_exit
+printf '%s' "$3" | grep -Eq '^([0-9]+|NF(-[0-9]+)?)$' || print_usage_and_exit
+printf '%s' "$4" | grep -Eq '^([0-9]+|NF(-[0-9]+)?)$' || print_usage_and_exit
+if echo "$1" | grep -q '^0\{1,\}$'; then
+  echo "$2" | grep -q '^0\{1,\}$' || print_usage_and_exit
 else
-  print_usage_and_exit
+  echo "$2" | grep -q '^0\{1,\}$' && print_usage_and_exit
 fi
-
-if [ $# -eq 4 ]; then
-  file='-'
-elif [ $# -eq 5 ]; then
-  if [ \( -f "$5" \) -o \( -c "$5" \) -o \( -p "$5" \) -o \
-       \( "_$5" = '_-' \)                                 ]; then
-    file=$5
-  else
-    print_usage_and_exit
-  fi
-fi
-if [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
-  echo "${0##*/}: Cannot open the file" 1>&2
+echo "$3" | grep -q '^0\{1,\}$' && print_usage_and_exit
+echo "$4" | grep -q '^0\{1,\}$' && print_usage_and_exit
+k1=$1; k2=$2; s1=$3; s2=$4
+shift 4
+case $# in
+  0) file='-'                                                         ;;
+  1) file=$1
+     [ \( -f "$file" \) -o \( -c "$file" \) -o \( -p "$file" \) ] || {
+       print_usage_and_exit
+     }                                                                ;;
+  *) print_usage_and_exit                                             ;;
+esac
+[ \( -r "$file" \) -o \( "_$file" = '_-' \) ] || {
+  printf '%s: Cannot open the file\n' "${0##*/}" 1>&2
   exit 1
-fi
+}
+case "$file" in ''|-|/*|./*|../*) :;; *) file="./$file";; esac
+
+
+# generate the awkcode of making keystring
+case "${s1%NF*}${s2%NF*}" in
+  "$s1$s2") keyfileds=$(awk -v s=$k1 -v e=$k2 '                          #
+                          BEGIN{if((s==0)&&(e==0)){print "\"\"";exit;}   #
+                                if( s>e          ){i=e; e=s; s=i;    }   #
+                                for(i=s;i<=e;i++ ){printf("$%d",i)   }}' |
+                        sed 's/\([0-9]\)\$/\1 FS $/g'                    )
+            ;;
+  '')       k1=$((0${k1#NF})); k2=$((0${k2#NF}))
+            keyfileds=$(awk -v s=$k1 -v e=$k2 '                          #
+                          BEGIN{if(s>e){i=e;e=s;s=i;}                    #
+                                for(i=s;i<=e;i++){printf("$(NF%d)",i)}}' |
+                        sed 's/)$/) FS $/g'                              |
+                        sed 's/(NF0)/NF/g'                               )
+            ;;
+  *)        keyfileds=$(printf 'getfldclstr(%s,%s)' "$k1" "$k2")
+            ;;
+esac
 
 
 # sum-up
-exec awk -F ' ' -v s=$3 -v e=$4 -v addcountfield=$count '
+exec awk -v addcountfield=$count '
 BEGIN {
   key0 = "";
+  split("", sum);
+  samekeylines = 0;
   _assert_exit = 0;
   ORS="";
 }
 
 {
-  if (NF < e) {
-    printf("'"${0##*/}"': There is a record which does not have enough number of fields!\n") > "/dev/stderr";
-    _assert_exit = 1;
-    exit _assert_exit;
-  }
-  key = "_" '"$keyfileds"';
+  if ('$s1'>'$s2') {e='$s1';s='$s2'} else {s='$s1';e='$s2'}
+  key = '"$keyfileds"';
   if (key == key0) {
-    for (i = s; i <= e; i++) {
-      sum[i] += $i;
-    }
+    for (i = s; i <= e; i++) {sum[i] += $i;}
     samekeylines++;
   } else {
-    if (NR > 1) {
-      print_smrecord();
-    }
-    for (i = s; i <= e; i++) {
-      sum[i] = $i;
-    }
+    print_smrecord();
+    for (i = s; i <= e; i++) {sum[i] += $i;}
     samekeylines = 1;
     key0 = key;
-    key0_for_print = '"$keyfileds"';
   }
 }
 
 END {
-  if (_assert_exit) {
-    exit _assert_exit;
-  }
+  if (_assert_exit) {exit _assert_exit;}
   print_smrecord();
 }
 
 function print_smrecord() {
-  printf("%s",key0_for_print);
-  dlm = (key == "_") ? "" : " ";
-  if (addcountfield) {
-    printf("%s%d", dlm, samekeylines);
-    dlm = " ";
-  }
-  for (i = s; i <= e; i++) {
-    print dlm sum[i];
-    dlm = " ";
+  if (samekeylines==0) {return;}
+  if (key0 == "") {
+    if (addcountfield) {
+                                print    samekeylines;
+      for (i = s; i <= e; i++) {print FS sum[i]      ;}
+    } else             {
+      for (i = s; i <= s; i++) {print    sum[i]      ;}
+      for (     ; i <= e; i++) {print FS sum[i]      ;}
+    }
+  } else          {
+                              print    key0           ;
+    if (addcountfield)       {print FS samekeylines   ;}
+    for (i = s; i <= e; i++) {print FS sum[i]         ;}
   }
   printf("\n");
+}
+
+function getfldclstr(fldnum1,fldnum2 ,i,str) {
+  str = $fldnum1;
+  if (fldnum1 <= fldnum2) {
+    for (i=fldnum1+1;i<=fldnum2;i++) {
+      str = str FS $i;
+    }
+  } else {
+    for (i=fldnum1-1;i>=fldnum2;i--) {
+      str = str FS $i;
+    }
+  }
+  return str;
 }' "$file"
diff --git a/COMMANDS.SH/tarr b/COMMANDS.SH/tarr
--- a/COMMANDS.SH/tarr
+++ b/COMMANDS.SH/tarr
@@ -7,14 +7,18 @@
 print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 		Usage   : ${0##*/} [-<n>] [-d[<string>]] [num=<n>] <file>
-		Version : Fri Jun 27 03:30:56 JST 2014
+		Version : Sat Jun 20 23:45:11 JST 2015
 		        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
 __USAGE
   exit 1
 }
 
 # Initialize
+set -u
+umask 0022
 PATH='/usr/bin:/bin'
+IFS=$(printf ' \t\n_'); IFS=${IFS%_}
+export IFS LANG=C LC_ALL=C PATH
 
 # parse the arguments
 n=1
@@ -29,7 +33,7 @@ for arg in "$@"; do
   i=$((i+1))
   case $arg in
     -[0-9]*)
-      echo "_${arg#-}" | grep '^_[0-9]\{1,\}$' >/dev/null
+      printf '%s\n' "${arg#-}" | grep -q '^[0-9]\{1,\}$'
       [ $? -eq 0 ] || print_usage_and_exit
       if [ $n_is_set -eq 0 ]; then
         n=${arg#-}
@@ -38,7 +42,7 @@ for arg in "$@"; do
       fi
       ;;
     num=[0-9]*)
-      echo "_${arg#num=}" | grep '^_[0-9]\{1,\}$' >/dev/null
+      printf '%s\n' "${arg#num=}" | grep -q '^[0-9]\{1,\}$'
       [ $? -eq 0 ] || print_usage_and_exit
       if [ $numopt_is_set -eq 0 ]; then
         numopt=${arg#num=}
@@ -60,14 +64,15 @@ for arg in "$@"; do
   [ $i -eq $# ] || print_usage_and_exit
   file=$arg
 done
-[ -n "$file" ] || file='-'
+case "$file" in '') file='-';; esac
 
 # validate the file arguments
 [ $n -gt 0 ] || print_usage_and_exit
 if [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
-  echo "${0##*/}: Cannot open the file" 1>&2
+  printf '%s: Cannot open the file\n' "${0##*/}" 1>&2
   exit 1
 fi
+case "$file" in ''|-|/*|./*|../*) :;; *) file="./$file";; esac
 
 # main
 export v1=$n
@@ -109,7 +114,7 @@ BEGIN {
     data = $0;
     for (i=1; i<=num; i++) {
       data = substr(data,length($i)+1);
-      sub(/^[[:blank:]]+/, "", data);
+      sub(/^[\t ]+/, "", data);
     }
     split(data, fld, d);
     # 2) extract
diff --git a/COMMANDS.SH/tateyoko b/COMMANDS.SH/tateyoko
--- a/COMMANDS.SH/tateyoko
+++ b/COMMANDS.SH/tateyoko
@@ -7,53 +7,60 @@
 print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [-d[<string>]] <file>
-	Version : Fri Jun 27 03:09:40 JST 2014
+	Version : Sun Jun 21 00:16:41 JST 2015
 	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
 __USAGE
   exit 1
 }
 
 # initialize
+set -u
+umask 0022
 PATH='/usr/bin:/bin'
+IFS=$(printf ' \t\n_'); IFS=${IFS%_}
+export IFS LANG=C LC_ALL=C PATH
 dummy_fldstr=''
 file=''
 
 # parse the arguments
-case "$1" in
-  -d*)
-    dummy_fldstr=${1#-d}
-    if [ "_$dummy_fldstr" = '_' ]; then
-      dummy_fldstr='*'
-    fi
-    shift
-    ;;
+[ $# -gt 0 ] && {
+  case "$1" in
+    -d*) dummy_fldstr=${1#-d}
+         case "$dummy_fldstr" in '') dummy_fldstr='*';; esac
+         shift
+         ;;
+  esac
+}
+case $# in
+  0) file='-'                                                   ;;
+  1) [ \( -f "$1" \) -o \( -c "$1" \) -o \( -p "$1" \) -o \
+       \( "_$1" = '_-' \)                                 ] && {
+       file="$1"
+     }                                                          ;;
+  *) print_usage_and_exit                                       ;;
 esac
-if [ \( -f "$1" \) -o \( -c "$1" \) -o \( -p "$1" \) -o \
-     \( "_$1" = '_-' \)                                 ]; then
-  file="$1"
-elif [ $# -lt 1 ]; then
-  file='-'
-else
-  print_usage_and_exit
-fi
 if [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
-  echo "${0##*/}: Cannot open the file" 1>&2
+  printf '%s: Cannot open the file\n' "${0##*/}" 1>&2
   exit 1
 fi
+case "$file" in ''|-|/*|./*|../*) :;; *) file="./$file";; esac
 
 # transpose the table
+export v0=${0##*/}
 export v1=$dummy_fldstr
 exec awk '
 BEGIN {
   max_nf = 0;
+  myname       = ENVIRON["v0"];
   dummy_fldstr = ENVIRON["v1"];
+  errmsg       = "There is a line which has a differnt number of fields.";
   _assert_exit = 0;
 }
 
 {
   if (NF > max_nf) {
     if ((NR > 1) && (length(dummy_fldstr) == 0)) {
-      print "'"${0##*/}"': There is a line which has a differnt number of fields." > "/dev/stderr";
+      printf("%s: %s\n", myname, errmsg) > "/dev/stderr";
       _assert_exit = 1;
       exit _assert_exit;
     }
@@ -70,7 +77,7 @@ BEGIN {
   }
   if (NF < max_nf) {
     if (length(dummy_fldstr) == 0) {
-      print "'"${0##*/}"': There is a line which has a differnt number of fields." > "/dev/stderr";
+      printf("%s: %s\n", myname, errmsg) > "/dev/stderr";
       _assert_exit = 1;
       exit _assert_exit;
     }
