cgi-name,cjoin*,delf,retu,self,ycat,han,calclock,comma,up3,mojihame,mojihame-h,mojihame-l,mojihame-p,tarr,yarr,zen,ysum:fixed a bug

diff --git a/COMMANDS.SH/retu b/COMMANDS.SH/retu
--- a/COMMANDS.SH/retu
+++ b/COMMANDS.SH/retu
@@ -7,7 +7,7 @@
 print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [-f] <file> ...
-	Version : Sat Jun 20 01:23:16 JST 2015
+	Version : Thu Jun 25 05:07:12 JST 2015
 	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
 __USAGE
   exit 1
@@ -45,36 +45,39 @@ BEGIN {
 '
 
 # parse arguments and count lines
-i=0
-for arg in "$@"; do
-  i=$((i+1))
-  if [ \( $i -eq 1 \) -a \( "_$arg" = '_-f' \) ]; then
-    foption=1
-    continue
-  elif [ \( "_$arg" = '_-'               \) -o \
-         \( "_$arg" = '_/dev/stdin'      \) -o \
-         \( "_$arg" = '_/dev/fd/0'       \) -o \
-         \( "_$arg" = '_/proc/self/fd/0' \)    ]
-  then
-    [ $use_stdin -ne 0 ] && print_usage_and_exit
-    use_stdin=1
-    file=$arg
-  elif [ \( -f "$arg" \) -o \( -c "$arg" \) -o \( -p "$arg" \) ]; then
-    file=$arg
-  else
-    print_usage_and_exit
-  fi
-  if [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
-    printf '%s: Cannot open the file "%s"\n' "${0##*/}" "$arg" 1>&2
-    exit 1
-  fi
-  case "$file" in ''|-|/*|./*|../*) :;; *) file="./$file";; esac
-  if [ $foption -ne 0 ]; then
-    filename=$arg awk "$awkcode_main" "$file"
-  else
-    filename=''   awk "$awkcode_main" "$file"
-  fi
-done
+case $# in [^0]*)
+  i=0
+  for arg in "$@"; do
+    i=$((i+1))
+    if [ \( $i -eq 1 \) -a \( "_$arg" = '_-f' \) ]; then
+      foption=1
+      continue
+    elif [ \( "_$arg" = '_-'               \) -o \
+           \( "_$arg" = '_/dev/stdin'      \) -o \
+           \( "_$arg" = '_/dev/fd/0'       \) -o \
+           \( "_$arg" = '_/proc/self/fd/0' \)    ]
+    then
+      [ $use_stdin -ne 0 ] && print_usage_and_exit
+      use_stdin=1
+      file=$arg
+    elif [ \( -f "$arg" \) -o \( -c "$arg" \) -o \( -p "$arg" \) ]; then
+      file=$arg
+    else
+      print_usage_and_exit
+    fi
+    if [ \( ! -r "$file" \) -a \( "_$file" != '_-' \) ]; then
+      printf '%s: Cannot open the file "%s"\n' "${0##*/}" "$arg" 1>&2
+      exit 1
+    fi
+    case "$file" in ''|-|/*|./*|../*) :;; *) file="./$file";; esac
+    if [ $foption -ne 0 ]; then
+      filename=$arg awk "$awkcode_main" "$file"
+    else
+      filename=''   awk "$awkcode_main" "$file"
+    fi
+  done
+  ;;
+esac
 if   [ \( -z "$file" \) -a \( $foption -ne 0 \) ]; then
   filename='-' awk "$awkcode_main"
 elif [ \( -z "$file" \) -a \( $foption -eq 0 \) ]; then
diff --git a/COMMANDS.SH/ycat b/COMMANDS.SH/ycat
--- a/COMMANDS.SH/ycat
+++ b/COMMANDS.SH/ycat
@@ -126,60 +126,63 @@ mktemp_instead_of_stdin () {
     exit 1
   fi
 }
-i=0
-for arg in "$@"; do
-  i=$((i+1))
-  case $i in
-    1) printf '%s\n' "$arg" | grep -q '^-[0-9]\{1,\}$' && {
-         numoption=${arg#-}
-         continue
-       }
-       ;;
-  esac
-  if [ \( "_$arg" = '_-'               \) -o \
-       \( "_$arg" = '_/dev/stdin'      \) -o \
-       \( "_$arg" = '_/dev/fd/0'       \) -o \
-       \( "_$arg" = '_/proc/self/fd/0' \)    ]
-  then
-    case $use_stdin in [^0]*) print_usage_and_exit;; esac
-    use_stdin=1
-    mktemp_instead_of_stdin
-    file=$tmpfile
-  elif [ \( -f "$arg" \) -o \( -c "$arg" \) -o \( -p "$arg" \) ]; then
-    str=$(printf '%s' "$arg" |
-          od -v -A n -t x1   |
-          tr -d ' \n'        )
-    if   echo "$hexed_filelist_readonce" | grep -Fq " $str "; then
-      printf '%s: Must not be set an irregular file two times\n' "${0##*/}" 1>&2
-      exit 1
-    elif echo "$hexed_filelist"          | grep -Fq " $str "; then
-      tmpfile=$(mktempf0)
-      if [ $? -eq 0 ]; then
-        tmpfiles="$tmpfiles $tmpfile"
-        trap "rm -f $tmpfiles; exit" EXIT HUP INT QUIT PIPE ALRM TERM
-        ln -fs "$arg" "$tmpfile"
-      else
-        printf '%s: Cannot create a temporary file\n' "${0##*/}" 1>&2
-        exit 1
-      fi
+case $# in [^0]*)
+  i=0
+  for arg in "$@"; do
+    i=$((i+1))
+    case $i in
+      1) printf '%s\n' "$arg" | grep -q '^-[0-9]\{1,\}$' && {
+           numoption=${arg#-}
+           continue
+         }
+         ;;
+    esac
+    if [ \( "_$arg" = '_-'               \) -o \
+         \( "_$arg" = '_/dev/stdin'      \) -o \
+         \( "_$arg" = '_/dev/fd/0'       \) -o \
+         \( "_$arg" = '_/proc/self/fd/0' \)    ]
+    then
+      case $use_stdin in [^0]*) print_usage_and_exit;; esac
+      use_stdin=1
+      mktemp_instead_of_stdin
       file=$tmpfile
-    elif [ -f "$arg" ]; then
-      hexed_filelist="$hexed_filelist$str "
-      file=$arg
+    elif [ \( -f "$arg" \) -o \( -c "$arg" \) -o \( -p "$arg" \) ]; then
+      str=$(printf '%s' "$arg" |
+            od -v -A n -t x1   |
+            tr -d ' \n'        )
+      if   echo "$hexed_filelist_readonce" | grep -Fq " $str "; then
+        printf '%s: Must not be set an irregular file two times\n' "${0##*/}" 1>&2
+        exit 1
+      elif echo "$hexed_filelist"          | grep -Fq " $str "; then
+        tmpfile=$(mktempf0)
+        if [ $? -eq 0 ]; then
+          tmpfiles="$tmpfiles $tmpfile"
+          trap "rm -f $tmpfiles; exit" EXIT HUP INT QUIT PIPE ALRM TERM
+          ln -fs "$arg" "$tmpfile"
+        else
+          printf '%s: Cannot create a temporary file\n' "${0##*/}" 1>&2
+          exit 1
+        fi
+        file=$tmpfile
+      elif [ -f "$arg" ]; then
+        hexed_filelist="$hexed_filelist$str "
+        file=$arg
+      else
+        hexed_filelist_readonce="$hexed_filelist_readonce$str "
+        file=$arg
+      fi
     else
-      hexed_filelist_readonce="$hexed_filelist_readonce$str "
-      file=$arg
+      print_usage_and_exit
     fi
-  else
-    print_usage_and_exit
-  fi
-  if [ ! -r "$file" ]; then
-    printf '%s: Cannot open the file "%s"\n' "${0##*/}" "$arg" 1>&2
-    exit 1
-  fi
-  case "$file" in ''|-|/*|./*|../*) :;; *) file="./$file";; esac
-  filenames="$filenames$LF$file"
-done
+    if [ ! -r "$file" ]; then
+      printf '%s: Cannot open the file "%s"\n' "${0##*/}" "$arg" 1>&2
+      exit 1
+    fi
+    case "$file" in ''|-|/*|./*|../*) :;; *) file="./$file";; esac
+    filenames="$filenames$LF$file"
+  done
+  ;;
+esac
 filenames=${filenames#?}
 case "$filenames" in
   '') use_stdin=1
