ycat:fixed a bug and improved

diff --git a/COMMANDS.SH/ycat b/COMMANDS.SH/ycat
--- a/COMMANDS.SH/ycat
+++ b/COMMANDS.SH/ycat
@@ -7,23 +7,89 @@
 print_usage_and_exit () {
   cat <<-__USAGE 1>&2
 	Usage   : ${0##*/} [-<n>] <file1> <file2> ...
-	Version : Tue Oct 14 18:09:17 JST 2014
+	Version : Sun Jun 21 01:04:48 JST 2015
 	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
 __USAGE
   exit 1
 }
-# the alternative of the mktemp command
-which mktemp >/dev/null 2>&1 || {
-  mktemp_fileno=0
-  mktemp() {
-    (
-      mktemp_filename="/tmp/${0##*/}.$$.$mktemp_fileno"
-      mktemp_fileno=$((mktemp_fileno+1))
-      touch "$mktemp_filename"
-      chmod 600 "$mktemp_filename"
-      echo "$mktemp_filename"
-    )
+# the alternative of the "mktemp -t"
+mktempf0() {
+  # --- parameters, etc. ---------------------------------------------
+  num_of_digits=16  # Length of Random String
+  n=10              # Max Times of Retrying
+  chrs='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_'
+                    # Available letters
+  LF=$(printf '\\\n_');LF=${LF%_}
+  # --- call built-in mktemp if exists -------------------------------
+  type mktemp >/dev/null 2>&1 && {
+    mktemp -t tmp.${0##*/}.$$.XXXXXXXXXXXXXXXX
+    return $?
   }
+  # --- set the temporary directory ----------------------------------
+  Dir_tmp=$(set | grep -q ^TMPDIR= | sed 's/^[^=]\{1,\}=//');
+  case "$Dir_tmp" in
+    '') Dir_tmp='/tmp'      ;;
+    /)  Dir_tmp=''          ;;
+    *)  Dir_tmp=${Dir_tmp%/};;
+  esac
+  # --- mktemp loop --------------------------------------------------
+  while [ $n -ge 0 ]; do
+    # --- Generate Ramdom string -------------------------------------
+    # calculate the number of words which required
+    nw=$(echo "${num_of_digits}*l(${#chrs})/11.09+1" | # 11.09=ln(65536)
+         bc -l                                       |
+         sed 's/\..*$//'                             )
+    # make a random hexadecimal digit
+    if [ -c /dev/urandom ]; then
+      hstr=$(dd if=/dev/urandom bs=2 count=$nw 2>/dev/null |
+             od -A n -t x2 -v                              |
+             tr 'abcdef ' 'ABCDEF\n'                       |
+             tr -Cd 0123456789ABCDEF                       )
+    else
+      hstr=$( (ps -Ao pid,etime,pcpu,vsz; date)         |
+             od -t d4 -A n -v                           |
+             sed 's/[^0-9]\{1,\}/'"$LF"'/g'             |
+             grep '[0-9]'                               |
+             tail -n 42                                 |
+             sed 's/.*\(.\{8\}\)$/\1/g'                 |
+             awk 'BEGIN{a=-2147483648;}                 #
+                       {a+=$1;        }                 #
+                  END  {                                #
+                    srand(a);                           #
+                    for(i=0;i<'$nw';i++){               #
+                      printf("%02X",int(rand()*65536)); #
+                    }                                   #
+                  }'                                    )
+    fi
+    # make a random string from the hexadecimal digit
+    s=$(echo "obase=${#chrs};ibase=16;$hstr"                     |
+        bc                                                       |
+        tr -d '\\\n'                                             |
+        tr ' ' '\n'                                              |
+        awk 'BEGIN  {for(i=1;i<'$num_of_digits';i++){print 0;}}  #
+             /[0-9]/{print;                                   }' |
+        awk 'BEGIN  {ORS="";                                     #
+                     s="'"$chrs"'";                              #
+                     for(i=0;i<length(s);i++){                   #
+                       c[i]=substr(s,i+1,1);                     #
+                     }                        }                  #
+             /[0-9]/{print c[$0*1];           }'                 |
+        tail -c $num_of_digits                                   )
+    # --- Making the file path ---------------------------------------
+    Path_target="${Dir_tmp}/tmp.${0##*/}.$$.$s"
+    # --- Making the file --------------------------------------------
+    (set -C; umask 177; : > "$Path_target") 2>/dev/null || {
+      [ -f "$Path_target" ] && { n=$((n-1)); continue; }
+      n=-1; break;
+    }
+    break
+  done
+  # --- print error message when failed to make a file ---------------
+  case "$n" in -1) return 1;; esac
+  # --- print the path of the file -----------------------------------
+  printf '%s\n' "$Path_target"
+  # --- return successfully ------------------------------------------
+  return 0
 }
 # decide whether to use the alternative length of AWK or not
 if awk 'BEGIN{a[1]=1;b=length(a)}' 2>/dev/null; then
@@ -34,43 +100,48 @@ fi
 
 
 # initialize
+set -u
+umask 0022
 PATH='/usr/bin:/bin'
+IFS=$(printf ' \t\n_'); IFS=${IFS%_}
+export IFS LANG=C LC_ALL=C PATH
 numoption=1
 filenames=''
 use_stdin=0
 tmpfiles=''
 hexed_filelist=' '
-LF=$(printf '\012_'); LF=${LF%_}
+hexed_filelist_readonce=''
+LF=$(printf '\n_'); LF=${LF%_}
 
 
 # parse arguments
 mktemp_instead_of_stdin () {
-  tmpfile=$(mktemp -t "${0##*/}.XXXXXXXX")
+  tmpfile=$(mktempf0)
   if [ $? -eq 0 ]; then
     tmpfiles="$tmpfiles $tmpfile"
     trap "rm -f $tmpfiles; exit" EXIT HUP INT QUIT PIPE ALRM TERM
     cat > "$tmpfile"
   else
-    echo "${0##*/}: Cannot create a temporary file" 1>&2
+    printf '%s: Cannot create a temporary file\n' "${0##*/}" 1>&2
     exit 1
   fi
 }
 i=0
 for arg in "$@"; do
   i=$((i+1))
-  if [ $i -eq 1 ]; then
-    echo "_$arg" | grep '^_-[0-9]\{1,\}$' > /dev/null
-    if [ $? -eq 0 ]; then
-      numoption=$(echo "_$arg" | sed 's/^_-//')
-      continue
-    fi
-  fi
+  case $i in
+    1) printf '%s\n' "$arg" | grep -q '^-[0-9]\{1,\}$' && {
+         numoption=${arg#-}
+         continue
+       }
+       ;;
+  esac
   if [ \( "_$arg" = '_-'               \) -o \
        \( "_$arg" = '_/dev/stdin'      \) -o \
        \( "_$arg" = '_/dev/fd/0'       \) -o \
        \( "_$arg" = '_/proc/self/fd/0' \)    ]
   then
-    [ $use_stdin -ne 0 ] && print_usage_and_exit
+    case $use_stdin in [^0]*) print_usage_and_exit;; esac
     use_stdin=1
     mktemp_instead_of_stdin
     file=$tmpfile
@@ -78,27 +149,17 @@ for arg in "$@"; do
     str=$(printf '%s' "$arg" |
           od -v -A n -t x1   |
           tr -d ' \n'        )
-    if   echo "$hexed_filelist_readonce" | grep -F " $str " >/dev/null; then
-      echo "${0##*/}: Must not be set an irregular file two times" 1>&2
+    if   echo "$hexed_filelist_readonce" | grep -Fq " $str "; then
+      printf '%s: Must not be set an irregular file two times\n' "${0##*/}" 1>&2
       exit 1
-    elif echo "$hexed_filelist"          | grep -F " $str " >/dev/null; then
-      retry=100
-      while [ $retry -gt 0 ]; do
-        retry=$((retry-1))
-        tmpfile=$(mktemp -u -t "${0##*/}.XXXXXXXX")
-        if [ $? -eq 0 ]; then
-          ln -s "$arg" "$tmpfile" > /dev/null 2>&1
-          [ $? -ne 0 ] && continue
-          tmpfiles="$tmpfiles $tmpfile"
-          trap "rm -f $tmpfiles; exit" EXIT HUP INT QUIT PIPE ALRM TERM
-          break
-        else
-          echo "${0##*/}: Cannot create a temporary file" 1>&2
-          exit 1
-        fi
-      done
-      if [ $retry -eq 0 ]; then
-        echo "${0##*/}: Failed to create a temporary file" 1>&2
+    elif echo "$hexed_filelist"          | grep -Fq " $str "; then
+      tmpfile=$(mktempf0)
+      if [ $? -eq 0 ]; then
+        tmpfiles="$tmpfiles $tmpfile"
+        trap "rm -f $tmpfiles; exit" EXIT HUP INT QUIT PIPE ALRM TERM
+        ln -fs "$arg" "$tmpfile"
+      else
+        printf '%s: Cannot create a temporary file\n' "${0##*/}" 1>&2
         exit 1
       fi
       file=$tmpfile
@@ -113,82 +174,68 @@ for arg in "$@"; do
     print_usage_and_exit
   fi
   if [ ! -r "$file" ]; then
-    echo "${0##*/}: Cannot open the file \"$arg\"" 1>&2
+    printf '%s: Cannot open the file "%s"\n' "${0##*/}" "$arg" 1>&2
     exit 1
   fi
-  filenames="$filenames $file"
+  case "$file" in ''|-|/*|./*|../*) :;; *) file="./$file";; esac
+  filenames="$filenames$LF$file"
 done
-filenames=${filenames# }
-if [ -z "$filenames" ]; then
-  use_stdin=1
-  mktemp_instead_of_stdin
-  filenames=$tmpfile
-fi
+filenames=${filenames#?}
+case "$filenames" in
+  '') use_stdin=1
+      mktemp_instead_of_stdin
+      filenames=$tmpfile
+      ;;
+esac
 
 
 # awkcode : get the length of the UTF-8 string (it is not a byte number)
 awkcode_func_utf8strlen='
 # strlen for UTF-8 (preparation : you must call this before using utf8strlen)
-function utf8strlen_prep() {
-  utf8strlen_80_1 = sprintf("\200");
-  utf8strlen_C0_X = sprintf("\300");
-  utf8strlen_E0_2 = sprintf("\340");
-  utf8strlen_F0_3 = sprintf("\360");
-  utf8strlen_F8_4 = sprintf("\370");
-  utf8strlen_FC_5 = sprintf("\374");
-  utf8strlen_FE_6 = sprintf("\376");
-  utf8strlen_K_EF = sprintf("\357");
-  utf8strlen_K_BD = sprintf("\275");
-  utf8strlen_K_BE = sprintf("\276");
-  utf8strlen_K_A0 = sprintf("\240");
-  utf8strlen_K_C0 = sprintf("\300");
-  utf8strlen_K_80 = sprintf("\200");
+function utf8_prep() {
+  chr_80_1 = sprintf("\200");
+  chr_C0_X = sprintf("\300");
+  chr_E0_2 = sprintf("\340");
+  chr_F0_3 = sprintf("\360");
+  chr_F8_4 = sprintf("\370");
+  chr_FC_5 = sprintf("\374");
+  chr_FE_6 = sprintf("\376");
+  chr_K_EF = sprintf("\357");
+  chr_K_BD = sprintf("\275");
+  chr_K_BE = sprintf("\276");
+  chr_K_A0 = sprintf("\240");
+  chr_K_C0 = sprintf("\300");
+  chr_K_80 = sprintf("\200");
 }
 
 # strlen for UTF-8 (main)
-function utf8strlen(str) {
-  utf8strlen_ = 0;
-  for (utf8strlen_i = 1; utf8strlen_i <= length(str); utf8strlen_i++) {
-    utf8strlen_++;
-    utf8strlen_letter=substr(str, utf8strlen_i, 1);
-    if (utf8strlen_letter < utf8strlen_80_1) {
-      continue;
-    } else if (utf8strlen_letter < utf8strlen_C0_X) {
-      utf8strlen_--;
-      continue;
-    } else if (utf8strlen_letter < utf8strlen_E0_2) {
-      utf8strlen_i++;
-    } else if (utf8strlen_letter < utf8strlen_F0_3) {
-      if (utf8strlen_letter == utf8strlen_K_EF) {
-        utf8strlen_letter2 = substr(str, utf8strlen_i+1, 1);
-        if (utf8strlen_letter2 == utf8strlen_K_BD) {
-          utf8strlen_letter3 = substr(str, utf8strlen_i+2, 1);
-          if ((utf8strlen_letter3 >= utf8strlen_K_A0) &&
-              (utf8strlen_letter3 <  utf8strlen_K_C0)  ) {
-            utf8strlen_--;
-          }
-        } else if (utf8strlen_letter2 == utf8strlen_K_BE) {
-          utf8strlen_letter3 = substr(str, utf8strlen_i+2, 1);
-          if ((utf8strlen_letter3 >= utf8strlen_K_80) &&
-              (utf8strlen_letter3 <  utf8strlen_K_A0)  ) {
-            utf8strlen_--;
-          }
+function utf8strlen(str, len,i,l1,l2,l3) {
+  len = 0;
+  for (i = 1; i <= length(str); i++) {
+    len++;
+    l1=substr(str, i, 1);
+    if      (l1 < chr_80_1)   {       continue;
+    } else if (l1 < chr_C0_X) {len--; continue;
+    } else if (l1 < chr_E0_2) {i++;
+    } else if (l1 < chr_F0_3) {
+      if (l1 == chr_K_EF) {
+        l2 = substr(str, i+1, 1);
+        if (l2 == chr_K_BD) {
+          l3 = substr(str, i+2, 1);
+          if ((l3 >= chr_K_A0) && (l3 < chr_K_C0)) {len--;}
+        } else if (l2 == chr_K_BE) {
+          l3 = substr(str, i+2, 1);
+          if ((l3 >= chr_K_80) && (l3 < chr_K_A0)) {len--;}
         }
       }
-      utf8strlen_i += 2;
-    } else if (utf8strlen_letter < utf8strlen_F8_4) {
-      utf8strlen_i += 3;
-    } else if (utf8strlen_letter < utf8strlen_FC_5) {
-      utf8strlen_i += 4;
-    } else if (utf8strlen_letter < utf8strlen_FE_6) {
-      utf8strlen_i += 5;
-    } else {
-      utf8strlen_--;
-      continue;
-    }
-    utf8strlen_++;
+      i += 2;
+    } else if (l1 < chr_F8_4) {i += 3;
+    } else if (l1 < chr_FC_5) {i += 4;
+    } else if (l1 < chr_FE_6) {i += 5;
+    } else                    {len--;  continue;}
+    len++;
   }
-  return utf8strlen_;
+  return len;
 }
 '
 
@@ -199,10 +246,10 @@ awkcode_main1_get_maxwidthes='
 function arlen(ar,i,l){for(i in ar){l++;}return l;}
 
 BEGIN {
-  utf8strlen_prep();
+  utf8_prep();
 
   filenames = ENVIRON["v1"];
-  split(filenames, filename);
+  split(filenames, filename, "\n");
 
   for (i = 1; i <= '$arlen'(filename); i++) {
     maxwidth[i] = 0;
@@ -222,7 +269,8 @@ BEGIN {
   print substr(str, 2, length(str) - 1);
 }
 '
-max_widthes=$(v1=$filenames awk "$awkcode_main1_get_maxwidthes$awkcode_func_utf8strlen")
+max_widthes=$(v1=$filenames                                              \
+              awk "$awkcode_main1_get_maxwidthes$awkcode_func_utf8strlen")
 
 
 # ycat
@@ -231,13 +279,13 @@ awkcode_main2_ycat='
 function arlen(ar,i,l){for(i in ar){l++;}return l;}
 
 BEGIN {
-  utf8strlen_prep();
+  utf8_prep();
 
   filenames   = ENVIRON["v1"];
   numoption   = ENVIRON["v2"];
   max_widthes = ENVIRON["v3"];
-  split(filenames, filename);
-  split(max_widthes, max_width);
+  split(filenames  , filename , "\n");
+  split(max_widthes, max_width      );
 
   margin = "";
   for (i = 0; i < numoption; i++) {
